### ISSUE TITLE
PDFi mockup järgi esimene versioon

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/kestame#10]

**Comment by infokujur** [comment]
Lisandusid logode failid, logode kausta.

**Comment by moll** [comment]
Logod jaluses? @katjadanilova, neid teil vektoris ja/või valgena ka leidub? Praegune sinine lõvi + must tekst sinisel taustal küll hea kombo ei tule. :)

**Comment by katjadanilova** [comment]
@moll tõepoolest :) leidsin must-valgeid versioone, lisasin kausta. Kultuurimini ja Sisemini logosid nad lubavad kasutada valgena (kas saaksid muuta värvi, veebilehel on neil ainult must olemas). EL logo on ainult must-valge või sinine-valge - aga must-valge peaks ok olema?

**Comment by moll** [comment]
@katjadanilova: Must-valged vast ajavad asja kenasti ära. Kust need leidsid ja kas seal neid SVG-dena ka oli PDFi ja Illustratori asemel? Kahtlustan, et mitte.

**Comment by katjadanilova** [comment]
@moll ei olnud, jah. leidsin siit: https://www.valitsus.ee/et/logofailid/otsing?title=kultuuriministeerium

**Comment by moll** [comment]
Gotcha.

Btw, midagi peaks varsti esilehele tagasijõudmise lingiga ka ette võtma. Sain su meili ettepanekust kasutada "Kogukondlikud arutelud #kestame" pealkirja alles aru, et see pole lehe, vaid saidi pealkiri. See tuli küll üllatusena, sest see asub ja paistab täpselt nagu (alam)lehe pealkiri. Tavaliselt on saidi pealkiri selliselt ainult esilehel ning mujal taandub ta peamenüüsse.

Peamenüü saaks vist ka natuke horisontaalsemalt lühemaks teha. Sõna "Arutelu" leiab sealt topelt ning saidi pealkirjast, ükskõik, kuhu ta ka ei jää, on ehk mõistetav, et "Korraldajale" on "arutelu" kontekstis. Lühem peamenüü ehk mahuks portree-vormis tahvlile ilma kahte rida kasutamata. Tahvli kasutajaid ma hamburger-menüü õudusega küll karistada ei tahaks. :) Moblale mahuks pealkirja alla paar linki ära küll. Kui nad kõik hamburgeri alla peita, ei vaata neid küll keegi.

PS. Kui veel hamburgerit ei vihka, siis https://www.nngroup.com/articles/hamburger-menus/ on äkki abiks antipaatia loomisel. :)

**Comment by katjadanilova** [comment]
![algatusest](https://user-images.githubusercontent.com/41726243/43274632-53a705c2-9108-11e8-8005-c7cbdb2f717d.png)
vaata palun, kas mõtlesid midagi sellist? et avalehel "avaleht" menüüs ei ole, aga ilmub siis, kui oled teistel lehtedel? Pealkirjad sellisel juhul liiguvad nö headerisse ning sellisel juhul on "Kogukondlikud arutelud #kestame" nagu alamlehe pealkiri. 
Menüü tegin lühemaks, olen nõus su argumentidega. Seda on selles mock'upis näha, vahetan ka failides ära.
Hamburgeri veel ei vihka, aga aitäh lingi eest, oli kasulik lugemine. Kas olemasoleva uue menüü annab mahutada moblale ilma hamburgerita? või mõtlen edasi?

**Comment by katjadanilova** [comment]
siin ka link mõlemale lehele: https://drive.google.com/drive/folders/1bmq0bNVgIveD7BdFkl0GBVxpQKL_82BB

**Comment by moll** [comment]
@katjadanilova: Peaegu. Ma pakuks ka umbes sellist varianti välja (lingid paremal võivad muutuda):
![screenshot from 2018-07-27 01-29-54](https://user-images.githubusercontent.com/156837/43296736-9f923aa4-913c-11e8-9db5-d4ae6fe09797.png)

Lükkasin ka work-in-progress versiooni https://kestame.rahvaalgatus.ee lehele konkreetsemateks aruteludeks üles. Mobiilile veel kohandamata, "probleemist" leht poolik, siit-sealt vaja veel joondada jms.

>  Hamburgeri veel ei vihka, aga aitäh lingi eest, oli kasulik lugemine. Kas olemasoleva uue menüü annab mahutada moblale ilma hamburgerita? või mõtlen edasi?

Saidi pealkirja (mis töötab ka avalehe lingina) saab kuvada mobiilis lehe ülal. Selle alla mahub tavaliselt umbes 3--4 horisontaalset linki (wrappima ei hakkaks). Kui kontaktinfo leht jääb peegeldama täpselt jalust, soovitan ka selle välja jätta. "Ideekorje" juures oli aga Google Docsis küsimus "(kas staatilisel lehel peidetud?)"). Jätsin ta otsuseni hetkel ka välja. Neljale lingile menüü tõenäoliselt ei taandu (kuigi kui saaksite, oleks see vast hea kõigile), kuid kui valida kolm enim olulist linki, saab need moblas välja tuua ning ülejäänud saia vahele peita. :)

Nelja sisulehe tekstid tõstsin ka Docsi. "Probleemist" lehe teised sektsioonid veel puudu. Vaatan, kas need õnnestub ühte faili pista või peab tehnilistel põhjustel (erinevad sektsioonid erineva taustaga) eraldi failidesse liigutama.

**Comment by katjadanilova** [comment]
aitäh lingi eest! näeb täitsa kena välja :) saatsin meeskonnale esimeseks tagasisideringiks.

menüüst:
1) logo "#kestame" sobib. meeskond arutab, kas äkki tahavad "#kuidasmekestame". Annan teada.
2) "Ideekorje" kuvada
3) "Kontakt" on kahtlane, sest sinna võib veel inimesi lisanduda. Hetkel las olla peidetud.

Kuidas suhtud sellesse, et mõni menüülink teha alammenüüdega? Mida see tähendaks mobla jaoks?
Kas selline (äkki liiga palju ruumi võtab?)
<img width="1388" alt="screenshot 2018-07-27 14 15 05" src="https://user-images.githubusercontent.com/41726243/43318371-2ee64bac-91a9-11e8-8e0c-08587018fbf5.png">

või selline (koos väikese noolega):
<img width="1410" alt="screenshot 2018-07-27 14 19 25" src="https://user-images.githubusercontent.com/41726243/43318386-432ebacc-91a9-11e8-8ef7-1b91c685eed1.png">

Kui gruppeerida, siis võiks nii teha: 
Algatusest -> Algatusest 
                   -> Probleemist
                   -> Kontakt
Arutelud    -> Kalender 
                  -> Korraldajale
Ideekorje

**Comment by moll** [comment]
Oleneb valikute arvust. Praeguse nelja-viiega pole mujal kui moblas peita vaja. Mu seisukoht üldjuhul on lehtede arvu vähendamise poolt ja seda uute külastajate pärast, kes ei oska informatsiooni tõenäoliselt nii granulaarselt kategoriseerida kui selle autorid. Meie kontekstis võib näiteks segane olla "Algatusest" ja "Probleemist" lehtede vahe. Võiks ju mõelda, et "algatusest" leht räägib probleemist, mida ta lahendab, enne kui lahenduse detailisse hüppab. Aga õnneks on tegu veel väikese relatiivselt hoomatava saidiga.

Notarize'i infoarhitektuur tundub selles valguses üpris kehv --- "Customer Support" on ometi sama, mis "Knowledge Center", mis omakorda sama, mis "FAQ". "Availability" on täiesti infotühi pealkiri jne (Nielsen+Norman on linkide nimetamisestki palju kirjutanud: https://www.nngroup.com/articles/information-scent/).

**Comment by katjadanilova** [comment]
Jätame siis hetkel nii nagu ta on. Lisandub hetkel ainult "Ideekorje". Ma arutan ka võimalust Algatusest ja Probleemist koos rääkida. 

Notarize tõin välja menüü kujunduse näitena, mitte nimetamise :)

**Comment by moll** [comment]
Lisasin ka esmase mobiili- ja tahvliversiooni. Praegu ilma peidetud menüüta, kuniks lingid selginevad. Häirivad lingid päises pisikeses 320px laias telefonis ei tundu. Vähemalt kohe näha, millistest lehtedest sait koosneb.

Ideekorje tõin tagasi. Sisult on ta ka natuke hõre.

"Probleemist" lehe teised sektsioonid lisasin ka Google Docsi. Igat valget-halli sektsiooni ümbritseb õige pisut HTMLi, sest ilma selleta ei saanud taustavärvi implementeerida. Kui soovite sektsioone ümber tõsta, lisada või eemaldada, saate seal esinevat `white-section` ja `grey-section` vastavalt soovile muuta. Videote placeholderid jätsin hetkel välja, lootuses, et sinna ilmuvad varsti päris videod.

Hetkel jään tagasisidet ootama ja lasen teil tekstidega töötada.

**Comment by moll** [comment]
Ahjaa, toetajate logod jalusest on veel puudu. Lisan need ka varsti.

**Comment by moll** [comment]
Venekeelse lehe tekstid tuleks ka ilmselt lisada või's esilehe link eemaldada.

**Comment by katjadanilova** [comment]
Tänan Sind! Ma süvenen veel ja annan teistele aega ka vaadata, korjan kõik ettepanekud korraga ja siis annan Sulle tagasisidet. Ilmselt järgmise nädala alguses. 
Vaatasin telefonist ja mulle meeldis - näeb kena välja ja menüü ei häiri üldse. 

Venekeelsed tekstid on saadetud tõlkesse, peaksid varsti lisanduma. Annan varsti ka teada teistest asjadest, mis hetkel meie poolt puudu on (videod, pdf'id, joonised).

**Comment by katjadanilova** [comment]
@moll paar küsimust:
1) esmaspäeval tahaksime näidata lehte toetajatele, selleks on meil logosid vaja. Jõuad lisada?
2) kas SEO peale oled jooksvalt mõelnud? ma palun meie partnereid mainida veebilehte nende lehtedel, aga hea oleks ka muude asjade peale mõelda (sitemap ja keywords?). Keywords võiksid olla: kestame, algatus, inimvara, rahvastik, arutelu, ideekorje.

**Comment by moll** [comment]
Heip

1. Lisasin kultuuri- ja siseministeeriumi logod jalusesse. Kas Euroopa Liidu lipp oli ka sinna mõeldud? Mõni toetaja veel?
2. Sitemapi all mõtled faili otsingumootorile, kus on kõik lehed kirjeldatud? Kergesti tehtav, kuid kahtlustan, et need viis lehte, mis meil on, leiab iga otsimootor tavalise külastusega üles. :) Keywordside otstarbe kohta ma ei oska öelda. Google väidetavalt ei kasuta neid üldse (https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html).

**Comment by katjadanilova** [comment]
hei!

1) hea! jah, lipp on ka sinna mõeldud. rohkem toetajaid ei ole.
2) hetkel google ei leia meie lehte. mis oleksid sinu sammud?

**Comment by katjadanilova** [comment]
@moll 
palun võimalusel viia need muudatused sisse enne homset (07.08) keskpäeva.

- [x] viimane EL logo. Tekst logode juures peab ka teistsugune olema: Projekti kaasrahastavad Euroopa Liit Varjupaiga -, Rände- ja Integratsioonifondi kaudu ning Eesti Vabariigi Siseministeerium.

- [x] uuendasime md failid - kas need jõustuvad automaatselt? hetkel on seal avalehe tekstid puudu, kas edastan muudatusi sulle otse?

domeeni nimeks jääb kestame, aga arutelu pealkirjana ja tekstide sees mujal kasutaks siis #kuidasmekestame. See tuleks siis veebilehel ühtlustada:
- [x] nn. logo peaks olema #kuidasmekestame 
- [x] avalehe pealkiri peaks olema Kogukondlikud arutelud #kuidasmekestame

- [x] Üldine joondus - esilehel ok, aga teistel lehtedel paigast ära (pealkiri vasakul ja sisutekst paremal). Teksti laius võiks olla sama, mis avalehel. 

- [x] avalehe nuppudega osa joondus: joonis, pealkiri ja nupp on ok, tekst on paigast ära. keskmine nupp "osalen" võiks olla samal tasandil teistega.

**Comment by moll** [comment]
>  uuendasime md failid - kas need jõustuvad automaatselt? hetkel on seal avalehe tekstid puudu, kas edastan muudatusi sulle otse?

Nii palju automaatselt, et kui ütled, saavad nad käesolevasse _reposse_ kopeeritud. Milliseid esilehe tekste aga mõtled? Sissejuhatust ülal? See on praegu tõesti vaid https://github.com/rahvaalgatus/kestame/blob/master/content/home.haml failis. Kui läheb tihedamaks muutmiseks, saab Markdowni välja viia.

> hetkel google ei leia meie lehte. mis oleksid sinu sammud?

Google'il eksisteerib "Add Your Website" leht kuskil, mille kaudu saate saidi eksistentsist teada anda, kuid leitavust see ilma mujalt viitamisteta leitavust ei garanteeri küll.

>  Üldine joondus - esilehel ok, aga teistel lehtedel paigast ära (pealkiri vasakul ja sisutekst paremal). Teksti laius võiks olla sama, mis avalehel.

Võime teistel lehtedel proovida pealkirja keskele panna või pealkirja alguse viia tekstiga samale joonele. Esilehe laius (kus tekst on mitmes tulbas) on paragrahvide jaoks aga liiga lai --- pikki ridu on kehv lugeda. Praegu on see u 80 tähemärki, mis on juba ideaalist, 60-70, suts üle. 

>  avalehe nuppudega osa joondus: joonis, pealkiri ja nupp on ok, tekst on paigast ära. keskmine nupp "osalen" võiks olla samal tasandil teistega.

Need võiks vast joondada küll, jah.

**Comment by moll** [comment]
Uuendasin ka tekste. Vaata ka oma silmaga üle, et näevad välja sellised, nagu ootasite.

**Comment by moll** [comment]
Kas ELi logo peaks ka kuskile linkima?

**Comment by katjadanilova** [comment]
> Võime teistel lehtedel proovida pealkirja keskele panna või pealkirja alguse viia tekstiga samale joonele. Esilehe laius (kus tekst on mitmes tulbas) on paragrahvide jaoks aga liiga lai --- pikki ridu on kehv lugeda. Praegu on see u 80 tähemärki, mis on juba ideaalist, 60-70, suts üle.

Proovime pealkirja alguse viia tekstiga samale joonele. Kõlab hästi.

> See on praegu tõesti vaid https://github.com/rahvaalgatus/kestame/blob/master/content/home.haml failis.

Õige! unustasin. Tegin seal lühikese paranduse praegu. Kui tekstid on valmis, panen neid ise sinna.

> Uuendasin ka tekste. Vaata ka oma silmaga üle, et näevad välja sellised, nagu ootasite.

logo on #kuidasmekestame (hetkel "me" puudu keskel)
muu on hea.

> Kas ELi logo peaks ka kuskile linkima?

ei. jäin mõtlema, et äkki näeb paremini välja, kui kõik logod on ühel real, mitte veerus? kas mahuvad ära?

**Comment by moll** [comment]
> jäin mõtlema, et äkki näeb paremini välja, kui kõik logod on ühel real, mitte veerus? kas mahuvad ära?

Hetkel peaksid piisavalt laial ekraanil olema nad reas, tahvlil ja moblal veerus. Kitsal ekraanil kolm kõrvuti ei mahtunud. Tahvli ja läpaka ekraani vahel võib esineda koht, kus kaks on kõrvuti ja kolmas uuel real...

> logo on #kuidasmekestame (hetkel "me" puudu keskel)

Oih, "me" kadus lugedes tõesti ära. Parandasin.

**Comment by katjadanilova** [comment]
Hommik!

Mõned asjad veel:

- [x] avalehe tekstid github'is uuendatud.
- [x] mobiilis sõidavad jalus logod kontakti peale
- [x] lehele Algatusest on vaja joonist lisada (kus hetkel on ainult pealkiri, ettepanekute teekond poliitika kujundajateni): https://drive.google.com/drive/folders/1a8mSaKQ7a_nmn7e2GHmVcLy6xmzQuU8m

**Comment by moll** [comment]
>  mobiilis sõidavad jalus logod kontakti peale

Andestust. Tegin ühe korrektuuri peale mobiili vaatamist, mis nad mobiilis ikka kõrvuti jättis. Parandatud!

> > logo on #kuidasmekestame (hetkel "me" puudu keskel)

> Oih, "me" kadus lugedes tõesti ära. Parandasin.

Hakkasin mõtlema, kas see valesti lugemine ei pruugi teistelgi juhtuda? Eesti keeles on "me" juba verbi käändelõpust järeldatav ja toimetamisharjumusega inimesed võivad asesõnad harjumusest ära jätta. 

>  lehele Algatusest on vaja joonist lisada (kus hetkel on ainult pealkiri, ettepanekute teekond poliitika kujundajateni): https://drive.google.com/drive/folders/1a8mSaKQ7a_nmn7e2GHmVcLy6xmzQuU8m

Ega seda SVG-na ei ole?

**Comment by katjadanilova** [comment]
> Hakkasin mõtlema, kas see valesti lugemine ei pruugi teistelgi juhtuda? Eesti keeles on "me" juba verbi käändelõpust järeldatav ja toimetamisharjumusega inimesed võivad asesõnad harjumusest ära jätta.

mina ka hääletasin kahe käega #kestame eest, aga tuli selline lõplik otsus :)

> Ega seda SVG-na ei ole?

Kuna need on InDesigni failid, siis svg-d ei ole seal. Vaata, äkki mõni meeldib rohkem. Ta teeb ümber.
<img width="906" alt="image001" src="https://user-images.githubusercontent.com/41726243/43770867-3728f076-9a46-11e8-90da-41675c6ccbdf.png">


- [x] kui pdf'id ikkagi sobivad, siis Probleemist lehele nuppude taga on uuendatud materjalid siin:
https://drive.google.com/drive/folders/1a8mSaKQ7a_nmn7e2GHmVcLy6xmzQuU8m

**Comment by moll** [comment]
> mina ka hääletasin kahe käega #kestame eest, aga tuli selline lõplik otsus :)

Ja pikem #kuidaskestame, kuid ilma "me"-ta, ka ei saavutanud populaarsust?

> Kuna need on InDesigni failid, siis svg-d ei ole seal. Vaata, äkki mõni meeldib rohkem. Ta teeb ümber.

Naljakas, et InDesign SVG-d ei ekspordi. Teen sellest Sketchiga SVG. Tundub, et loeb vektorkomponendid PDFist välja.

**Comment by moll** [comment]
Jäin PNGi juurde, sest SVG Sketchist peale teksti kurvideks muutmist oli suuruseks pool mega vs PNGi 250kB. Võimalik, et skeem tuleks tekstist laiemaks teha, sest teksti-laiusena on ta loetamatult väike. Tegin ka lingiks, et vähemalt saaks suuremalt näha.

Lisasin ka PDFid "Probleemist" lehele.

**Comment by moll** [comment]
Nüüd peaks vist senise tagasiside soovid täidetud olema, või jäi mul midagi kahe silma vahele?

**Comment by katjadanilova** [comment]
> Lisasin ka PDFid "Probleemist" lehele.

tee palun, et link avaneks uues aknas.

> Võimalik, et skeem tuleks tekstist laiemaks teha, sest teksti-laiusena on ta loetamatult väike. Tegin ka lingiks, et vähemalt saaks suuremalt näha.

arusaadav, et on väike, aga näeb OK välja mu meelest :)

- [x] lisa palun venekeelne leht ka, lõpuks valmis!
https://drive.google.com/drive/folders/1ZEpel-DYceWEWPIGgJszHkw8n_KmDar6

> Nüüd peaks vist senise tagasiside soovid täidetud olema, või jäi mul midagi kahe silma vahele?

Jaah! Ainult venekeelne leht hetkel jäänud. 
Saadan nüüd meeskonnale edasi.

**Comment by katjadanilova** [comment]
- [x] on olemas ka joonis venekeelsele lehele: https://drive.google.com/drive/folders/1a8mSaKQ7a_nmn7e2GHmVcLy6xmzQuU8m

**Comment by katjadanilova** [comment]
> Google'il eksisteerib "Add Your Website" leht kuskil, mille kaudu saate saidi eksistentsist teada anda, kuid leitavust see ilma mujalt viitamisteta leitavust ei garanteeri küll.

see on nüüd Search Console osa. automaatselt ei andnud võimalust seadistada, seega palun sind vaadata (google analytics - admin - all products - search console)

**Comment by moll** [comment]
Vene keel ka üleval: https://kestame.rahvaalgatus.ee/сохранимся/. Lehe URLiks panin hetkel lihtsalt "сохранимся" (eeldatavasti "kestame"), kuid kuna ma vene keelt ei räägi, siis vbla üksikult ta ei sobi.

> tee palun, et link avaneks uues aknas.

Tehtav, aga kõigepealt pean uurima, mis probleemi uues aknas avamine lahendab? :) Mobiilis kipuvad uued aknad (või tab'id) relatiivselt tülikad olema, sest kui akna avamist ei märka, lakkab "back" nupp töötamast ning ja tuleb ette võtta retk menüüdes. iOSis vähemalt. Androidikate "back" nupp töötab ilmselt isegi "üle" tab'ide. Värskemad brauserid kuvavad PDFe juba nagu veebilehti nkn ja üksikutele, kes kasutavad korporatiivbrausereid lauaarvutis, kus see funktsionaalsus võib maha keeratud olla, saavad "download" akna ka ilma uue tab'i avamata. Uute akende küsimata avamine on ometi põhjus, mis popup blockerid kümmekond aastat tagasi turule tulid. ;)

**Comment by moll** [comment]
Faktilehe linke oli venekeelsel kolm --- üks vähem kui eestikeelsel. See oli taotluslik?

**Comment by moll** [comment]
Linkisin ka kestame.rahvaalgatus.ee domeeni Analyticsiga ja vajutasin kindluse pärast "Fetch as Google" nuppu Search konsoolis. Ma ei oska öelda, millise konto külge seos läks, nii et kui sul seal miski ligipääs puudub, anna teada.

**Comment by moll** [comment]
@katjadanilova, kae ka: https://github.com/rahvaalgatus/rahvaalgatus/issues/92.

**Comment by katjadanilova** [comment]
> Tehtav, aga kõigepealt pean uurima, mis probleemi uues aknas avamine lahendab? :)

tead, tegelikult tekkis palve, sest hetkel ei ole arusaadav, mis asi on faktileht ja mis juhtub, kui nupule vajutad. seega tundus ausam, et inimest ei visata lehelt välja, vaid et see leht avaneb uues tabis. Mõtlesin ja pakun lahendust mu murele, mis tundub mobiili kasutajasõbralikum: kas äkki lisame viidet pdfile, nt nii: FAKTILEHT (pdf). Siis teab inimene hästi, et seda annab eraldi aknas avada soovi korral. mis arvad?

> Ma ei oska öelda, millise konto külge seos läks, nii et kui sul seal miski ligipääs puudub, anna teada.

miski ikka ei toimi, jah. 
<img width="1440" alt="screenshot 2018-08-14 11 49 41" src="https://user-images.githubusercontent.com/41726243/44081822-599c4ba4-9fb8-11e8-854b-9f117d585b3f.png">

>  Vene keel ka üleval: https://kestame.rahvaalgatus.ee/сохранимся/.

me teeme reeglina Eestis nii: https://kestame.rahvaalgatus.ee/rus, sest kuigi Venemaal kasutavad kirillitsat url'ides, eestivenelased ei ole sellega harjunud.

**Comment by moll** [comment]
Su viimased soovid jäid Arvamusfestivali käigus kuidagi tahaplaanile. Andestust.

> tead, tegelikult tekkis palve, sest hetkel ei ole arusaadav, mis asi on faktileht ja mis juhtub, kui nupule vajutad. seega tundus ausam, et inimest ei visata lehelt välja, vaid et see leht avaneb uues tabis. Mõtlesin ja pakun lahendust mu murele, mis tundub mobiili kasutajasõbralikum: kas äkki lisame viidet pdfile, nt nii: FAKTILEHT (pdf). Siis teab inimene hästi, et seda annab eraldi aknas avada soovi korral. mis arvad?

Hea meelega. Uuendasin Markdownid ja lükkasin koos kaardiga https://kestame-next.rahvaalgatus.ee-le ülevaatamiseks. 

> > Ma ei oska öelda, millise konto külge seos läks, nii et kui sul seal miski ligipääs puudub, anna teada.
>
> miski ikka ei toimi, jah.

Tänaseni katki?

> > Vene keel ka üleval: https://kestame.rahvaalgatus.ee/сохранимся/.
> 
> me teeme reeglina Eestis nii: https://kestame.rahvaalgatus.ee/rus, sest kuigi Venemaal kasutavad kirillitsat url'ides, eestivenelased ei ole sellega harjunud.

`/rus` tundub kole halva nn lõhnaga URL. Kui mitte kirillitsa, siis kas Ladina tähestikuga vene fraas ei oleks parem? Mõlemal juhul, kuna URL on natuke juba ehk Internetis liigelnud, muudan ta redirectiga, et eksisteerivad lingid katki ei läheks. ;)

**Comment by moll** [comment]
@katjadanilova, nähes, et liigutasid _Projects_ vaates _issue_ "Valmis" tulpa, siis kas sellest võib järeldada, et kirillitsa URLi osas mõtlesid ümber ja jääb praegune? :) Kui nii, siis kas võib sellegi _issue_ tehtuks lugeda?

**Comment by katjadanilova** [comment]
ei mõelnud ümber, aga unustasin.

> tundub kole halva nn lõhnaga URL. Kui mitte kirillitsa, siis kas Ladina tähestikuga vene fraas ei oleks parem? 

äkki siis nii: /o-nas ?

**Comment by moll** [comment]
Vabalt. Muudan ja suunan vana sinna.

**Comment by moll** [comment]
https://kestame.rahvaalgatus.ee/сохранимся/ suunab nüüd /o-nas-ile.
