### ISSUE TITLE
I ankeet - Registreeri arutelule ankeet embeddida veebi

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/kestame#11]
Mocup: https://drive.google.com/open?id=1H1GxBRoCdZDGA2uAFpUeX-yE0YmznvSi

Tekst on peaaegu sama, mis hetkel üleval (ilma esimese kahte ja viimase lauseta).

Värvid: päise värv on #0078ff, aga vot tausta värviga mul küsimus - automaatselt näitab ankeet, et ei võimalda taustafooni muuta. Seega sobiks hall, mis neil on (#f6f6f6), kui aga on võimalik muuta, siis meie enda sobiks paremini: #f0f1f2. Variant on ka teha margins nii väikesteks, et taustavärvi pole üldse.

Asuma hakkab "Korraldajale" alamlehel.

**Comment by infokujur** [comment]
Ankeet ise: https://docs.google.com/forms/d/1DXwRgCv2gBbN8WH86a4TlLbzMHhus5kPfp936na3cQw/edit

**Comment by infokujur** [comment]
Siin tuleb tähelepanu juhtida - kuidas saab läbi  ankeedi koordinaadid kaardile.
Kuna siin käib meie inimene ankeedi tulemused enne üle (ja tõstab siis lehele, kus skript käib). Ehl võib teha ka nii, et koordinaadid sisetab see inimene, kui Forms ise automaatselt aadressist Lat/Lon ei tee.

**Comment by moll** [comment]
Näeb päris okei välja kui embeddida: https://kestame-next.rahvaalgatus.ee/korraldajale/
Praegu eraldi URLi peal, kuid kui sobib, võin ka laivi lükata.

**Comment by moll** [comment]
Lisasin Google Spreadsheeti ka tulba, mis automaatselt aadressi koordinaatideks teeb. Võite alati käsitsi üle kirjutada.

**Comment by katjadanilova** [comment]
me pidime lisama veel ühe küsimuse, nüüd on ankeet veidi pikemaks läinud ja alumine osa ei mahu täies ulatuses. muidu aga kena ja saame laivi lükata.

**Comment by moll** [comment]
> me pidime lisama veel ühe küsimuse, nüüd on ankeet veidi pikemaks läinud ja alumine osa ei mahu täies ulatuses. muidu aga kena ja saame laivi lükata.

Google'i _embeddimise_ kood sisaldas ja vajas täpset kõrgust, nii et ma ei imesta. Ega see väga jätkusuutlik pole tõesti --- muudavad mõne piksli võrra stiile ja jälle ei klapi. Uuendan igal juhul.

Kas mõte on vorm lükata laivi enne kaarti või on teil mõni päris arutelu juba tabelisse sisestada?

**Comment by moll** [comment]
Lisatud küsimus peaks vist olema radio-buttonitega. Praegu saab mõlemad teineteist välistasvad variandid valida.

**Comment by moll** [comment]
FYI: Ootan kahe toimunud arutelu sisestamist arutelude tabelisse, et siis midagi laivi lükata. Sain aru, et teil oli tahe eile juba arutelusid koguma hakata.

**Comment by katjadanilova** [comment]
hei! olen lähetuses ja kuna see on mul vabatahatlik projekt, siis aeg-ajalt pole piisavalt resurssi, et koheselt vastata. vabandan. mul oli üks päris arutelu, mida ka sisestasin ja palun, et tiimiliikmed ülejäänud ka ülesse paneksid. aga arvan, et saame juba laivi lükata.

**Comment by moll** [comment]
Aa, kõik hästi ja hea teada. Ma ei olnud lihtsalt kindel, kas veeretasin palli enda väljakult teie poolele arusaadavalt. :)

**Comment by katjadanilova** [comment]
arusaadavalt küll. nüüd on esimesed kolm arutelu üleval.

palun lase laivi veebileht.

**Comment by moll** [comment]
Lükkasin vormi laivi. Jätkame kas https://github.com/rahvaalgatus/kestame/issues/12 -s või teeme uued issue'd.
