### ISSUE TITLE
I ankeet - Registreerunute näitamine kaardil (sisend registreerumisankeedi tabelist, mida korrastatakse)

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/kestame#12]
- Kui toimub registreerumine, siis kaart ei uuene st on vaja luua alaleht, kuhu tiimi liige toob andmed käsitsi, kui on registreeringu üle vaadanud
- Kaardil on erineva värviga ikoonid, sõltuvalt kuupäevast (kui arutelu läbi, värv ja kastikese sisu muutuvad, aga kõik jäävad kaardile viimase päevani)
- Mocup kaardi visandiga: https://drive.google.com/open?id=1i5saxm8NdGux_MX7W6f573W35jyuwCuG

**Comment by infokujur** [comment]
Tn on mõtekas teha, et skript käib pärimas ühelt alalehelt mingi intervalliga ja tulemused tulevad teisele alalehele, kust skripti allikale valemitega kokku jooksutame. @moll - Mis saa arvad?

**Comment by katjadanilova** [comment]
ikoon, mida kasutasin mockupis: https://icons8.com/icon/set/Map-Marker/all

**Comment by katjadanilova** [comment]
kaardirakendus: mapbox.com

**Comment by moll** [comment]
> Kui toimub registreerumine, siis kaart ei uuene st on vaja luua alaleht, kuhu tiimi liige toob andmed käsitsi, kui on registreeringu üle vaadanud

Ehk andmed ei tule mitte vormi tabelist, vaid teisest käsitsi hallatavast. Okei. Tehke üks lisaks, andke mulle igaks juhuks testimiseks ka muutmisõigused ja heitke link. :)

> Tn on mõtekas teha, et skript käib pärimas ühelt alalehelt mingi intervalliga ja tulemused tulevad teisele alalehele, kust skripti allikale valemitega kokku jooksutame. @moll - Mis saa arvad?

Mõtled skripti, mis võtab ülalnimetatud tabelist andmed ja kuvab kaardil? Vabalt.

**Comment by infokujur** [comment]
@moll Panin kirja teele

**Comment by moll** [comment]
@katjadanilova: Mockupis oleva halli tooni kaardi said Mapboxi kaudu või krabasid mujalt illustratsiooniks?

**Comment by katjadanilova** [comment]
halli tooni sain Mapboxi kaudu. see on nende üks võimalustest.

**Comment by moll** [comment]
WIP: https://kestame-next.rahvaalgatus.ee/kalender/
Puudu valdade järgi grupeerimine.

Täislaiuses kalender näeb visuaalselt äge, aga Mapboxi rakenduse vaikimisi käitumine zoomida rulliku peale tähendab, et kaardini jõudes ei pruugi enam lehel alla kerida saada, kui a) ei tea, et peab hiirt valgel alal hoidma või b) valget ala ei ole nähtaval. Üpris frustreeriv. Praegu ei tundu ka, et seda saaks Google Mapsi järgi konfida control-i allhoidmise peale. :/ 

Millistena sa toimunud ürituste markereid ette kujutasid, @katjadanilova?
Mis mõte detailsemal kui toimunud-toimumas arutelude filtreerimisel on, kui neid tuleb vaid paarkümmend?
Keelt pole hetkel arutelude nimekirjas mainitud...

**Comment by katjadanilova** [comment]
> Puudu valdade järgi grupeerimine.

sa mõtled seda, et ei ole hetkel nimekirjas valdada järgi gruppeerimist? või mida täpsemalt? 

> kaardini jõudes ei pruugi enam lehel alla kerida saada

on jah, frustreeriv. kas on siis mõtekas proovida seda mitte täislaiuses teha? kas kasutamismugavus muutub sellega?
vaatasin, et frustreeriv on ka see, et kui avaned lehe esimest korda, siis markereid pole kohe näha, enne kui sa ei zoomi veits lähemale..samuti ei ole kusagil ka märguannet, et kaardi annab zoomida. kuidas sellega nüüd on, kas kõik kasutajad saavad juba sellest ise aru või on heaks reegliks ikkagi näidata "+" ja "-" paremas nurgas? 

> Millistena sa toimunud ürituste markereid ette kujutasid,

need, mis alles tulevad - sinised; need, mis on juba toimunud - rohelised

> Mis mõte detailsemal kui toimunud-toimumas arutelude filtreerimisel on, kui neid tuleb vaid paarkümmend?

neid peaks olema kokku 100 ning siis, kui arutelu on läbi, me peaksime vahetama info kastikeses "tutvu arutelu tulemustega" lingile. Sellest, kuidas me tulemusi kuvame, räägime 01.10 Maarja-Leenaga. Ilmselt siis oleme ka konkreetsemad.

> Keelt pole hetkel arutelude nimekirjas mainitud...

see on minu viga! peaks olema keel ka kindlasti.

**Comment by katjadanilova** [comment]
selline mõte tuli: avalehel häirib see võimatus hiirega liikuda edasi ilmselt kõige rohkem. kas me saaksime nii teha nt, et enne tuleb osa tulpadega "Algatuses saab igaüks osaleda" ja alles siis kaart? Sellisel juhul inimene näeb ikkagi kõik oma osalemisvõimalused enne ja kui soovib, siis saab edasi liikuda.

**Comment by moll** [comment]
> selline mõte tuli: avalehel häirib see võimatus hiirega liikuda edasi ilmselt kõige rohkem. kas me saaksime nii teha nt, et enne tuleb osa tulpadega "Algatuses saab igaüks osaleda" ja alles siis kaart? Sellisel juhul inimene näeb ikkagi kõik oma osalemisvõimalused enne ja kui soovib, siis saab edasi liikuda.

Tegin nii seda kui ka vähendasin kaardi laiust. Toonisin kaardist vasakule jääva ala mereroheliseks ja parema halliks, mis jätab peaaegu täislaiuses kaardi mulje, kuid loodetavasti lubab inimestel pisut paremini lehel liikuda. 

> > Millistena sa toimunud ürituste markereid ette kujutasid,
>
> need, mis alles tulevad - sinised; need, mis on juba toimunud - rohelised

Ok, vaatan kuskilt sarnase markeriikooni ümbervärvimiseks. Icons8 oma ainult rasterformaadis ja mustalt.

Kuna esilehe lugeri järgi on kaks arutelu olevat juba toimunud, siis äkki lisaks need ka tabelisse, et laivi lükates saaks minu test-arutelud sisulistematega asendada? :)

> sa mõtled seda, et ei ole hetkel nimekirjas valdada järgi gruppeerimist? või mida täpsemalt?

Täpselt seda --- valdasid pealkirjadena.

> samuti ei ole kusagil ka märguannet, et kaardi annab zoomida. kuidas sellega nüüd on, kas kõik kasutajad saavad juba sellest ise aru või on heaks reegliks ikkagi näidata "+" ja "-" paremas nurgas?

Mõtlesin sellele, kuid ei jõud lisamiseni. Nüüd tehtud. Näha ikka aadressil https://kestame-next.rahvaalgatus.ee/kalender/.

**Comment by katjadanilova** [comment]
> Täpselt seda --- valdasid pealkirjadena.

kas soovid, et see oleks kusagil failis eraldi kirjas? või lisame tabelisse veergu?

**Comment by moll** [comment]
Teeme vist praegu tabelisse veeruga. Kindlasti saab selle ka kuidag koordinaatidest läbi GSheetsi tuletada kui numbrid suureks lähevad, aga esialgu võib käsitsi panna. :)

Kuvame Harjumaa alati esimeseks ja pärast tähestiku järjekorras?

**Comment by katjadanilova** [comment]
jah, võiks nii. 
kas ma panen ise tabeli viimase veeruna (K veerg)?

**Comment by moll** [comment]
Võid panna ka aadressi kõrvale. Järjekord pole oluline. :)

**Comment by katjadanilova** [comment]
tehtud :)

**Comment by moll** [comment]
Esilehel on korraldatud arutelude arv. Kas see tuleks kuidagi arutelude arvuga siduda? Siis peaks ka osalenud inimeste arvu tabelisse koguma.

**Comment by katjadanilova** [comment]
selleks on teine ankeet, mida me veebilehele ei embeddi, vaid saadame käsitsi. aga peale seda, kui tulemused on sisestatud, on neid tõepoolest vaja ka veebilehel näidata. me räägime sellest pikemalt Maarja-Leenaga 01.10 ja siis saame täpsema kirjelduse anda.

**Comment by moll** [comment]
Lükkasin praegused arutelud üles: https://kestame.rahvaalgatus.ee. Puudu veel värvilised kaardimarkerid.

Kolme arutelu jaoks veel filtreerimist ei lisanud, kuid vaatamata sellele võiks juba mõelda toimunud arutelude visuaalsele eraldusele. Äkki tuleviku omade pealkiri siniseks ja/või toimunud omade tekst kursiivi?

Esilehel kuvame vaikimisi kõiki või ainult tuleviku arutelusid?

**Comment by moll** [comment]
Kolmega pole veel näha, aga sorteerisin maakondade arutelud (koodis) nii, et esimestena tuleksid tuleviku omad, varaseim enne, ning teisena toimunud, hilisem enne. Ükskõik, millise visuaalse indikaatori neile valime, on nii neid kergem silmadega eristada.

**Comment by katjadanilova** [comment]
> Kolme arutelu jaoks veel filtreerimist ei lisanud, kuid vaatamata sellele võiks juba mõelda toimunud arutelude visuaalsele eraldusele. Äkki tuleviku omade pealkiri siniseks ja/või toimunud omade tekst kursiivi?

äkki tuleviku omad siniseks ja toimunud roheliseks? peaks selgituse kuhugi ka välja tooma. 

> Esilehel kuvame vaikimisi kõiki või ainult tuleviku arutelusid?

ma kuvaks kõiki, aga samuti värvilise erinevusega.

aitäh Sulle kaasa mõtlemast!!

**Comment by katjadanilova** [comment]
@moll:
1) kuidas meil hetkel script töötab, ehk kui tihti ta seal tabelist infot võtab ja veebilehel avaldab? Muutsime hommikul asju ja nad ei ole veel nähtavad, seepärast uurin. 
2) meil hetkel on lehel kolm arutelu, mis on juba möödas ja varsti (täna-homme) tulevad uued. Kas tegeled palun nende mummukeste värvide ja tulevad/toimunud filtriga?

**Comment by moll** [comment]
Hei

Lisan homme esimese asjana värvid kaardile! 

> äkki tuleviku omad siniseks ja toimunud roheliseks? peaks selgituse kuhugi ka välja tooma.

Üks variant on ka tuleviku omad siniseks ja teised hallikaks teha. Vähem kontrastne värv nagu hall kipub mujalgi nn vanade asjade kuvamiseks olema. Selline kombo on ehk intuitiivsem kui kindlalt legendi vajavad kirkad toonid.

> kuidas meil hetkel script töötab, ehk kui tihti ta seal tabelist infot võtab ja veebilehel avaldab? Muutsime hommikul asju ja nad ei ole veel nähtavad, seepärast uurin.

See on seepärast, et momendil midagi automaatselt seda ühte nupuvajutust lehe uuenduseks ei tee. :)  Tahtsin enne pea ärapööramist näha, kas mõne uue arutelu sisestamine läheb edukalt. Me lihtsa automatiseerimise negatiiv, et vigu näeksite alles laivis. :) Võin aga käivitada --- nt iga 15 minuti tagant? Võime's kokku leppida, et võtad ühendust, kui midagi laivis ei näe õige välja ja ei taha 15 minutit jälle muutuseks oodata.

**Comment by katjadanilova** [comment]
> Üks variant on ka tuleviku omad siniseks ja teised hallikaks teha.

jah, olen nõus. võiks ka nii teha.

> Võin aga käivitada --- nt iga 15 minuti tagant? 

see sobiks hästi!

**Comment by moll** [comment]
Kui saaks mõne tuleviku-arutelu ka tabelisse, siis näeksid, kas ja kuidas hall ja sinine koos klapivad. :) Muidu valmisolek laivis.

**Comment by moll** [comment]
Väike probleem on meil koordinaatidega. Lisasin varasemalt GSheetsi custom-funktsiooni `GEOCODE`, mis D tulbast aadressi alusel koordinaadid tekitab (stiilis `=GEOCODE(D1)`) . Kahjuks CSV-d eksportides GSheets funktsioone ei jooksuta ja tulba sisu kaob. Kummaliselt aga töötab see natuke aega peale viimast tabeli muutmist, nii et esialgu viga ei märganud. Lahendasin preagu nii, et liigutasin funktsiooni tulp edasi ning kopeerisin tulemused (Paste Values) K tulpa.

**Comment by katjadanilova** [comment]
hmm..meil nüüd üks arutelu lisandus, nii et saame vaadata, kuidas sellega läheb :)

**Comment by moll** [comment]
Muudatust märgati ja oleks ise laivigi läinud, kui poleks kuupäev olnud ootamatus formaadis ning koordinaadid puudu. :) Kuupäeva sai, jah, vormi vaikimisi järjestusest ISO järjestusse pandud (YYYY-MM-DD), sest USA variant oli veaohtlik ---  kuu ja päev lähevad vahetusse, nagu mul alguses augusti aruteludega läks --- ning polnud kindlust, et GSheets alati ise USA juurde jääb. Koordinaatide probleemi lahendust ma vbla ei kirjeldanud https://github.com/rahvaalgatus/kestame/issues/12#issuecomment-426294419 -s piisavalt --- need tuleb eelnimetatud GSheetsi tehnilise puuduse tõttu kahjuks käsitsi K tulbast Paste Values'sega "coordinates" tulpa liigutada.  

Luban teil n-ö harjutamiseks ise parandada. :)

**Comment by moll** [comment]
Kuna paistad AFK, siis korrigeerisin praegu ise. Kui keegi teine peale sinu sisestab, informeeri teda ka skriptide vormieelistustest. :)

**Comment by moll** [comment]
@katjadanilova, mäletaksin nagu kuskilt, et palusid esilehe arutelude loendaja ka tabeliga ühendada, kuid ei leia seda ühestki GitHub _issue_'st hetkel. Tegin selle täienduse kiirelt ära. Osalejate arv jätkuvalt staatiline.

Kas muu kaardi ümber on praegu okei? Kui nii, võib vast _issue_ sulgeda.

**Comment by katjadanilova** [comment]
palusin jah .. isegi hiljuti uuesti sellest justkui kirjutasin. igatahes - aitäh! 
kas osalejate arvu teed ka automaatseks?

kaardi kohta on ainult üks küsimus jäänud - kas saab niimoodi teha, et kui leht avaneb, siis see kaart on kohe veits rohkem sisse zoomitud (et oleks ikoone ka näha kohe). hetkel justkui ei ole seal midagi.

**Comment by moll** [comment]
> palusin jah .. isegi hiljuti uuesti sellest justkui kirjutasin. igatahes - aitäh!

Palun-palun. Ja leidsin, kus viimati teemaks tuli: https://github.com/rahvaalgatus/kestame/issues/6
 
> kas osalejate arvu teed ka automaatseks?

Võib. Uus tulp samas arutelude tabelis sobiks?

> kaardi kohta on ainult üks küsimus jäänud - kas saab niimoodi teha, et kui leht avaneb, siis see kaart on kohe veits rohkem sisse zoomitud (et oleks ikoone ka näha kohe). hetkel justkui ei ole seal midagi.

Zoom levelit saab muuta. Esialgu valisin ta selliselt, et terve Eesti näha oleks. Ikoonid peaksid nähtaval olema aga igal tasemel. Kas sul kuvab erinevalt kui mul (Firefox Linuxi alt)?

![screenshot from 2018-10-17 14-18-15](https://user-images.githubusercontent.com/156837/47092893-86a76c00-d217-11e8-9f37-312f116ddaae.png)

**Comment by katjadanilova** [comment]
meil kolmel on nii:
<img width="1080" alt="screenshot 2018-10-18 09 49 56" src="https://user-images.githubusercontent.com/41726243/47136088-44376b00-d2bb-11e8-9f18-47a08eadbbbc.png">

**Comment by katjadanilova** [comment]
selgus veel üks huvitav asi:
kui arutelud toimuvad samas kohas, aga erineval ajal, siis kaardil on nähtav ainult üks ja esimene. Kui esimene arutelu möödub, siis teine automaatselt vist muutub möödunuks ka. See juhtus Saaremaa aruteludega:

2018-10-15 | 4:00:00 PM | Kuressare vabakontor "EDUkontor" | Saaremaa | Eesti keeles | Saaremaa sädeinimeste arutelu-läbimäng I | Maris Rebel | 56986981 | maris.rebel@gmail.com | 22.4848423;58.25310009999999 | 22.4848423;58.25310009999999 

2018-10-28 | 2:00:00 PM | Kuressaare vabakontor "EDUkontor" | Saaremaa | Eesti keeles | Saaremaa sädeinimeste arutelu-läbimäng II | Maris Rebel | 56986981 | maris.rebel@gmail.com | 22.4848423;58.25310009999999 | 22.4848423;58.25310009999999 |

**Comment by moll** [comment]
> meil kolmel on nii:

Mis brauserid need on? Huvitav, miks Mapbox erinevalt käitub. Kas alait esimese zoomimise peale ilmuvad? Isegi kui zoomid välja?

>  kui arutelud toimuvad samas kohas, aga erineval ajal, siis kaardil on nähtav ainult üks ja esimene. Kui esimene arutelu möödub, siis teine automaatselt vist muutub möödunuks ka. See juhtus Saaremaa aruteludega:

Ahjaa. Identsete koordinaatidega arutelud kuvatakse tõesti üksteise peal ja ju siis must sinisel. Kalendri lehelt näeb, et üks teist muul viisil ei mõjuta: https://kestame.rahvaalgatus.ee/kalender/. Mis sellele hea lahendus olla võiks? Kuvada alati toimumata arutelu pealmisena? Klikkimise peale detailid ühte popuppi panna? Kui Saaremaa on ainus koht, kus juhtub, siis võib ka arenduseta häkki proovida ning koordinaati õige pisut muuta, et nad kaardil üksteise peal ei oleks.

**Comment by katjadanilova** [comment]
>  Kuvada alati toimumata arutelu pealmisena? Klikkimise peale detailid ühte popuppi panna

jah, võiks nii teha. sest ei tea hetkel, äkki mitte ainult Saaremaal sama asi ette tuleb.

> Mis brauserid need on? Huvitav, miks Mapbox erinevalt käitub. Kas alait esimese zoomimise peale ilmuvad? Isegi kui zoomid välja?

ei tea, kas tegid midagi, aga nüüd ka väga zoomitud out näitab kõik kenasti.

> kas osalejate arvu teed ka automaatseks? Võib. Uus tulp samas arutelude tabelis sobiks?

uus tulp sobiks. arutelude tulemuste tabelis? või kus täpsemalt? hetkel peaks olema juba 6 arutelu ja 78 inimest.

**Comment by moll** [comment]
> > Kuvada alati toimumata arutelu pealmisena? Klikkimise peale detailid ühte popuppi panna
> 
> jah, võiks nii teha. sest ei tea hetkel, äkki mitte ainult Saaremaal sama asi ette tuleb.

Tehtud. Mapbox peaks nüüd tuleviku arutelusid kuvama toimunute peal.

> > Mis brauserid need on? Huvitav, miks Mapbox erinevalt käitub. Kas alait esimese zoomimise peale ilmuvad? Isegi kui zoomid välja?
> 
> ei tea, kas tegid midagi, aga nüüd ka väga zoomitud out näitab kõik kenasti.

Pole puutunud, kuid Mapbox ise võis telgitaga küll midagi korrigeerida.

> > kas osalejate arvu teed ka automaatseks? Võib. Uus tulp samas arutelude tabelis sobiks?
> 
> uus tulp sobiks. arutelude tulemuste tabelis? või kus täpsemalt? hetkel peaks olema juba 6 arutelu ja 78 inimest.

Arutelude registreerimise tabelis, sest selle põhjal kalender tehakse. Lisasin tulba ja panin hetkel esimesse "71", et lehele sama summa jääks. Saate õiged numbrid nullide asemele panna.

**Comment by katjadanilova** [comment]
selle ankeediga on veel üks küsimus tekkinud:

Katja, mis sa arvad, kas meil oleks mõtet veidi arutelude registreerimisvormi muuta - selliselt, et see näitaks ka prognoositava arutelu lõpu aja?
Kui see liiga palju nõuab aega, siis pigem mitte. Kui on aga väga lihtne ja mõne liigutuse küsimus, siis teeks ära. 

terv
Maris

Begin forwarded message:

From: Piret Jeedas <piret@ruumiloojad.ee>
Subject: Re: #kuidasmekestame arutelud Jõgevamaal
Date: 24. oktoober 2018 16:48.38 GMT+3
To: Maris Jõgeva <maris.jogeva@gmail.com>

Hei,

ma arvan, et on hea, kui sellel kaardil on selge info selle kohta, kui kaua see kestab.

Just edasises infos on see oluline!

Mina olen preagu juba kutsudes seda selgelt öelnud, aga eks inimestele tundub see ikkagi pikk:-).

P

**Comment by moll** [comment]
Kas see küsimus on mulle? Vabalt. Kas tahame kuvada ajavahemikku (19.00-22.00) või kirjeldada kestust otse (19.00, kestab ~2h)?

**Comment by katjadanilova** [comment]
ajavahemikku :) kas saame ise muuta või on sul kuidagi määratud täpselt, mis tulp mille eest veebilehel vastutab?

**Comment by moll** [comment]
Ikka täpselt määratud, kuid tulbapealkirja järgi. :) Kas täpsus tundides ajab asja ära? Siis võime teha lisatulba kestustega (näiteks "2" või "1.5") ja panen ta ajavahemikku kuvama.

**Comment by katjadanilova** [comment]
hea oleks, et ankeedi täitja saaks valida mis kl algab ja mis kl lõpeb ning arutelu juures me näitame "Toimub: kuupäev, kl 16:00-19.00" nt.

**Comment by moll** [comment]
Ankeet inimesel täitmiseks ja tabel, millest leht genereeritakse, on meil ju eraldi. Kuna kuupäev vajaks niikuinii korrigeerimist ISO formaati (YYYY-MM-DD), siis võime kuupäeva korrigeerimise asendada tundidesse tõlgendamisega. Saab ka lõpukuupäeva ja lõpukellaaja tulpadega, kuid arvan, et kestused on kindlamad --- kui keegi muudab alguskuupäeva, ei pea lõppu liigutama ega juhtu kunagi nii, et lõpp on enne algust.

**Comment by katjadanilova** [comment]
on jah, mingil määral eraldi. võime proovida ka nii nagu sina räägid teha.

**Comment by moll** [comment]
Panin `duration` tulba kella kõrvale. Kui mugavam ankeedist paste'ida, kui ta kuskil hiljem tuleb, võite liigutada. Lisan lõpukellaaja kuvamise ka varsti.

**Comment by moll** [comment]
On jäänud mainimata, et lõpukellaaja kuvamine sai laivi lükatud ka 5 päeva tagasi. Tabelis tunduvad aga kõik algatused jätkuvalt null kestusega. Lihtsalt Marisele teada andmata? Äkki tooks ta ka siia, et telefonimängu ei peaks mängima? :)
