### ISSUE TITLE
Arutelul väljatoodud probleemide visuaal

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/kestame#13]
Uus Eakuse-laadselt, kus ringi keskel kolm kategooriat ning ümber probleemid (suurus määratud olulisusest) ja nende pakutud lahendused lisakliki all.

**Comment by katjadanilova** [comment]
siin on värvid jaotatud nõnda, et iga valdkond (kokku on kolm valdkonda - sündivus, tööhõive ja ränne) on oma värvi. sündivus: #8b7883, tööhõive: #65a580; ränne: #2b7aa1

@moll kas peaks täpsemalt soovitud tulemust kirjeldama või on sul pilt olemas peas?

**Comment by moll** [comment]
@katjadanilova, gaks juhuks kinnitaksin siiski üle, kas sain nägemusest õigesti aru. :)

- [Uus Eakuse](https://uuseakus.rahvaalgatus.ee/)-laadselt sõõrik kolme kategooriaga keskel.
- Kas sõõriku sees peaks kategooriat kirjeldav tekst asetsema?
- Sõõriku ümber väiksemad (ka värvitud, eks?) ringid, mis kujutavad erinevaid aruteludel tõstatatud probleeme.
- Ringide keskel pakutud lahenduste arv.
- Ringide (ehk probleemide) olulisus tuli pakutud lahenduste arvust või peaks kuidagi teie poolt käsitsi määratud olema? 
- Ringidele vajutades või hiirega üle minnes kuvatakse aruteludel pakutud lahendusi. Seal edasi kuskile klikkida ei saa, eks?

Mida väiksemal ekraanil kuvada? Kas peidame üldse, kuvame nimekirja kujul või ootame, et külastaja zoomib sisse ja navigeerib visualisatsiooni ümber?

**Comment by katjadanilova** [comment]
Vastan iga punkti kohta eraldi: 
Uus Eakuse-laadselt sõõrik kolme kategooriaga keskel. - JAH
Kas sõõriku sees peaks kategooriat kirjeldav tekst asetsema? - täpselt ma ei mõista, kas see tähendab, et nt “sündimus” oleks ühe lausega lahti kirjutatud? Kas see visuaalselt mahub? Kui, siis igaks juhuks panen kohe kaasa ka tekstid, mida kasutame kolme fookusteema kirjeldamiseks. 
Sõõriku ümber väiksemad (ka värvitud, eks?) ringid, mis kujutavad erinevaid aruteludel tõstatatud probleeme - jah
Ringide keskel pakutud lahenduste arv - jah
Ringide (ehk probleemide) olulisus tuli pakutud lahenduste arvust või peaks kuidagi teie poolt käsitsi määratud olema? - see tuleb ankeedist. Igalt arutelult saame tulemusena teada, millised on igal teemal kolm kõige olulisemaks hääletatud probleemi
Ringidele vajutades või hiirega üle minnes kuvatakse aruteludel pakutud lahendusi. Seal edasi kuskile klikkida ei saa, eks? - jah. Iseküsimus on muidugi selles, kuidas lahendada, et kõigile probleemidele ei olegi pakutud lahendusi. Kuigi need võivad olla väga oluliseks peetud?


*********

SÜNDIMUSE TÕSTMINE
Ideed, mis aitavad Eesti peredel jõuda kahe ja enama lapseni
TARK RÄNNE
Ideed, mis aitavad väljarännet vähendada, tagasirännet soodustada ning kaasata väljast tulnud inimeste potentsiaali
INIMVARA TÕHUSAM KAASAMINE
Ideed, kuidas tööturult eemal olevaid inimesi paremini kaasata, tööviljakust tõsta, töid automatiseerida ning ümber- ja täiendõpet soodustada

**Comment by moll** [comment]
Nende mõne toimunud arutelu pealt saame natuke juba andmeid mängimiseks, eks? Tegin arutelude tulemuste tabelisse lehe "Probleemid" struktuuri ettepanekuga: Igal real üks probleem, kuid lahendused ühes tulbas reavahega eraldatud. Olulisus lihtsalt eraldi tulbas numbrina.
Kas see haakuks teie töövooga või on mõni teine struktuur käepärasem täitjale?

**Comment by moll** [comment]
Vahva --- tabelisse on ilmunud päris probleeme ja pakutud lahendusi!

Kahjuks aga kardan, et ringidega visualisatsioonivorm huvitava informatsiooni levikule kaasa küll ei aita. Kiire graafiline näidis, kuidas ta umbes lehel välja näeb:
![screen shot 2018-10-25 at 00 20 04](https://user-images.githubusercontent.com/156837/47469122-d0332080-d7ee-11e8-961f-095f9e437670.png)

Ütleksin, et sellises vormis on probleeme üpris piinarikas lugeda või avastada --- aja hiirega ringe taga ja püüa meeles pidada, millisele ringile oled vajutanud, millisele mitte. Numbrid ringides ei ole iseenesest mõistetavad ja läheksid suuruserinevusega (mida pildil näha pole) ilmselt vastuollu --- kas olulisem on "1"-ga, "4"-ga või hoopis suurem ring? Lugemine saab olema kohmakas, sest avanenud tekst katab ülejäänud ringid. Tahvlites nõuab see eriti agarat sõrmega vehkimist. Mobiilis pole keskmise sõõriku jaoks ruumi, ringide klikitavus pole ilmne ning popover on tõenäoliselt pikem kui ekraan ise --- leht lehes. 

Järeldan ma õigesti, et probleemide ja lahenduste avastamine ja lugemine on soovitud eesmärk? Miks mitte info lihtsalt nähtavale tuua? Kas kaalusite ka teisi visualisatsioone või lihtsalt info kuvamise viise? Kolm kategooriat haakuks hästi kolme tulbaga... Probleemid mahuksid nimekirjana ja ei vajaks lisaklikke. Lahendused aga ilmselt võivad olla lisakliki ja numbri all peidus.

**Comment by infokujur** [comment]
Oleme juba üsna lähedal:

Kiiruga vaatan - kui joonistasime kavandit, siis arutasime, et:
- ringi/kasti suurus = probleemi olulisus
- ringi/kasti pealkiri = probleemi nimi
- ringis/kastis pakutud lahenduste arv ja klikates nimekiri

**Comment by moll** [comment]
Kuhu "ringi pealkiri" läheb?

Ringide asemel kastid tekstiga on kindlasti parem, aga 24+ probleemi ei mahu praeguste pikkade fraasidega täies ära. Siis tasub keskmisest sõõrikust ära öelda ja olemegi tagasi kolme tulba või kaardi-laadse kujunduse juures (Rahvaalgatuse esilehe laadselt). :)

**Comment by infokujur** [comment]
Sama nagu siin visuaalil: https://uuseakus.rahvaalgatus.ee/

Kui fraas pikk, siis punktiir järgi. Nii palju teksti ei ole võimalik infograafikule nii ehk naa ära mahutada. Klikates on täispikk asi näha.

**Comment by infokujur** [comment]
Algne kavand ka siia
![15408091189051620567773](https://user-images.githubusercontent.com/12999094/47644391-aa9f7180-db76-11e8-93ed-fcd9a4836093.jpg)

**Comment by moll** [comment]
Maris:
> Küsin üle, kas Katja tehtud joonisest ja mu nädalavahetuse kritseldusest ei piisa? 

Kui täpne olla, siis oleme kirjeldanud lahenduse mustandi, kuid graafiliselt on lahtiseid või kinnitamata küsimusi. Näiteks:
- Kuidas lahendused mobiilis (laius u 320px) või portree laadis tahvlis (laius u 768px) välja näevad?
- Kuidas ristkülikud graafiliselt välja näevad?
- Kuidas lahenduste popover välja näeb?

Võime ka otsustada mitte otsustada ja teen esmalt enda äranägemise järgi. :)

@katjadanilova:
> Ristkülikud võiksid olla ühe laiusega. ma testisin, et vist peaksid kõik prooblemid olema piisavalt lühidalt sõnastatud, et mahuksid. Paigutatud nad võiksid olla kaootiliselt nö, et iga ringi värvi juures on selle värvi ristkülikud probleemidega.

Mahuvad ikka, sest pikem probleem teeks ristküliku lihtsalt kõrgemaks. Mõtled ka, et ristkülikud on horisontaalselt teineteise suhtes nihkes? Vaadates su enda mustandit (all), siis võib ennustada, et pruune "Sündimuse" ristkülikuid mahub maksimaalselt kõrvuti kaks. 6--8 probleemi puhul tuleb neid 3--4 rida. 1 rida mahub ilmselt ringi ümber, üks vasakule, üks paremale, kuid ringi kohal olevad? Näed neid ette täpselt keskel või pisut nihkes? Jne. :) 

![screenshot from 2018-10-30 14-01-16](https://user-images.githubusercontent.com/156837/47723371-4bac2c00-dc4c-11e8-8f47-c6bafb1db7a2.png)

Maris:
> Üks asi veel: ma ei peaks skriptiallikat torkima, aga lisasin sinna ikka ühe veeru “lahenduste arv”. Loodan, et sellest pigem kasu kui kahju.

Oh, ikka võid torkida, sest sinu jaoks peab täitmine ju mugav olema. :) Kui aga pakutud lahendused on igaüks niikuinii teises tulbas eraldi ridadel, siis on nende arv sealt tuletatav ja eraldi tulpa arvuga ignoreeritakse.

**Comment by marisjogeva** [comment]
Praegu ei ole lahendused igaüks eraldi real, vaid veerus E komadega eraldatud. Kas panen need eraldi ridadele?

**Comment by moll** [comment]
Pakkusin https://github.com/rahvaalgatus/kestame/issues/13#issuecomment-432053924 -s esialgu reavahed välja, aga suurt vahet ei ole. Komadega on teil tõenäoliselt raske, sest need kipuvad eesti keele lausetes esinema. Võid ise valida, kas semikoolonid, reavahed või mõni muu märgis.

**Comment by marisjogeva** [comment]
Kui jääb olemasolev lahendus, saan ettepanekud nummerdada, nt: 1. Inimesed olgu õnnelikud. 2. Elu saagu hea jne. Siis saab ehk mugavamalt üle tõsta?

**Comment by moll** [comment]
Numbrid teeksid selle isegi pisut raskemaks, sest siis tuleb neid eristada teistest lauses esinevatest numbritest, eemaldada nad enne kuvamist, et HTML oma tööd teha saaks jms. :) Kõige lihtsamad ongi kas reavahed või harva esinev interpunktsioon. Kui soovid, võime alati igale probleemi lahendusele tabelis oma rea pühendada, aga siis peaksid lahenduse ridade ees ka probleemid kirjas olema ja see võib sul/teil tülikas hallata olla.

**Comment by katjadanilova** [comment]
@moll ma võtan enda peale joonistamise, et sa saaksid natuke parema ettenägemuse, mida saame veel korra põrgutada ja siis juba töösse lasta. jäin haigeks, aga katsun täna täpsema versiooni valmis teha, sest tuli soov kõiki tulemusi eraldi lehele paigutada ja mitte kuvada neid avalehel. nii et ma katsun selle ideekorje mustandi teha.

**Comment by katjadanilova** [comment]
@moll võtsime aega ja mõtlesime asjad läbi. 
hetkel tundub mõistlik niimoodi teha: veits muudame Avalehe.
Avalehele lisandub nupp "tutvu tulemustega", mis viib lehele, mis hetkel kannab nime "Ideekorje". Värv: #ff4800
[Avaleht 30 10 2018.pdf](https://github.com/rahvaalgatus/kestame/files/2538659/Avaleht.30.10.2018.pdf)

nüüd kõik tulemused viskame hetkel "Ideekorje" lehele. Nimetame selle lehe "Tulemused" ümber. Sisu võiks olla nagu mock-up'il. 
Koosneb neljast osast: 
I osa jaoks teeb Maris teksti. Nupp tuleb laivi alles 23.11, aga võiksid selle planeerida (ta viitab google ankeedile, mida ei hakka embeddima).
II osa on meie juba tehtud sõnapilved. 
III osa on graafikud, mida seni polnud. Hetkel on tehtud pildina, aga võiks selle automaatiseerida (andmed on meie samast tulemuste tabelist, teema-probleem-olulisus tulbad). Kas on võimalik seda teha visuaalselt nii nagu pildil - et füüsiliselt võtab graafik ainult niipalju ruumi, aga klikitavate rubriigide all on kaks ülejäänud teemat? Iga teema tulbad on oma värvi, samu värve kasutame ka IV. osas. Probleem, ehk graafiku selgitav tekst, võiks mahuda kas tervikuna, või olla nähtav kui hiirega selle peale liigud. Kõik suurused ja font on joonise peal illustratiivsed - ehk peaksid olema meie tavalised.
IV osa - kiiruse ja lihtsuse huvides otsustasime siiski tavaliste tulbade kasuks. Näidatud võiksid olla ainult need, millele on pakutud lahendused. Selle osa kujundusest on visuaalselt täpsem. Meie värvid: Sündivus: #ff4800; Ränne: #808284; Tööhõive: #65a580. Lahenduste osa on hetkel tehtud mul sama värviga, lihtsalt opacity vähendatud (pildil on 18%). Shadow on must (x:0/y:2/blur:4). Nooli shadow on ka must (x:0/y:0/blur:5). Mõlemaid aga võid oma nägemuse järgi sättida. Ristküliku nurgad on raadiusega 4, kui avaneb aken selgitustega, siis alumised muutuvad 0ks. 

[tulemused copy.pdf](https://github.com/rahvaalgatus/kestame/files/2538717/tulemused.copy.pdf)

**Comment by katjadanilova** [comment]
Uued tekstid "Ideekorje" lehe jaoks on .md failis juba olemas.

**Comment by katjadanilova** [comment]
@moll Andri, on sul kommentaare või küsimuse? saame me sellega edasi minna?

**Comment by moll** [comment]
Hei! Hakkab looma.

>  III osa on graafikud, mida seni polnud. Hetkel on tehtud pildina, aga võiks selle automaatiseerida (andmed on meie samast tulemuste tabelist, teema-probleem-olulisus tulbad). Kas on võimalik seda teha visuaalselt nii nagu pildil - et füüsiliselt võtab graafik ainult niipalju ruumi, aga klikitavate rubriigide all on kaks ülejäänud teemat?

Saab nii automatiseerida kui ka tab'e teha. 

> Iga teema tulbad on oma värvi, samu värve kasutame ka IV. osas. Probleem, ehk graafiku selgitav tekst, võiks mahuda kas tervikuna, või olla nähtav kui hiirega selle peale liigud.

Kas numbrid värvitud ribadel viitavad pakutud lahenduste arvule või olulisusele? Eeldan, et nii number kui ka riba pikkus viitab lahenduste arvule ning olulisus määrab vaid järjekorra.

Kuidas see moblas välja võiks näha? Portree-tahvlis vist mahub isegi ära.

Ideenupp tuleb paari nädala pärast, aga tulemuste visualiseerimise ise võiks ASAP valmis teha ja laivi saada, eks?

**Comment by moll** [comment]
Mobiili küsimus võib kehtida ka lahenduste tulpade kohta, kuid eeldan, et ega seal me midagi enamat välja ei mõtle kui lihtsalt kolm tulpa üksteise järel. :)

**Comment by marisjogeva** [comment]
Vastan ühele: Kas numbrid värvitud ribadel viitavad pakutud lahenduste arvule või olulisusele? 
III osas on ainult probleemid ja olulisus (number ja ka riba pikkus)
IV osas näitab teksti ees olev number lahenduste arvu. 
Tulemuste visualiseerimise teeks jah nii ruttu kui võimalik ära ja kohe laivi. Kõik on juba põnevil ja ootavad. 



.

**Comment by katjadanilova** [comment]
mobiili osas: kas arvad, et selline pilt, nagu ma pakkusin, moblasse tervikuna ei mahu?
näiteks, võiks nii proovida, et moblas läheb tekst väiksemaks tabelis?

**Comment by katjadanilova** [comment]
> Mobiili küsimus võib kehtida ka lahenduste tulpade kohta, kuid eeldan, et ega seal me midagi enamat välja ei mõtle kui lihtsalt kolm tulpa üksteise järel. :)

jah!

**Comment by moll** [comment]
>  III osas on ainult probleemid ja olulisus (number ja ka riba pikkus)

PDFis on probleemid suvalises järjekorras. Kas need peaksid olema olulisuse järjekorras? 

> mobiili osas: kas arvad, et selline pilt, nagu ma pakkusin, moblasse tervikuna ei mahu?
> näiteks, võiks nii proovida, et moblas läheb tekst väiksemaks tabelis?

Mobiilis on ~320px horisontaalset ruumi ehk u kolmandik PDFi joonisest. See mahutab horisontaalselt enam-vähem kuus-seitse sõna 16px/17px fondiga. Probleemid mahuvad kahele reale küll, aga riba neist paremale mitte. Värvilise riba saaks iga probleemi alla tuua. Teksti ei tahaks väiksemaks teha, sest kahtlustan, et kõik lugejaskond pole esimeses nooruses.

**Comment by katjadanilova** [comment]
> Probleemid mahuvad kahele reale küll, aga riba neist paremale mitte. Värvilise riba saaks iga probleemi alla tuua.

see tundub ka sobilik lahendus!

**Comment by katjadanilova** [comment]
> PDFis on probleemid suvalises järjekorras. Kas need peaksid olema olulisuse järjekorras?

Maris arvas nii: Arvan, et ei pea. Tulba pikkus niikuinii näitab olulisust hästi. Aga kui see on lihtne teha, siis võib-olla on visuaalselt mõjusam, kui tulbad olulisuse järjekorras. 

> Probleemid mahuvad kahele reale küll, aga riba neist paremale mitte. Värvilise riba saaks iga probleemi alla tuua.

kas tahad, et me selle enne sinuga joonisel vaatame, või teeksid valmis ja siis vaatame? mulle tundub, et selline lahendus on OK, kui olen õigesti tekstist aru saanud :)

**Comment by moll** [comment]
> Aga kui see on lihtne teha, siis võib-olla on visuaalselt mõjusam, kui tulbad olulisuse järjekorras.

On lihtne.

> kas tahad, et me selle enne sinuga joonisel vaatame, või teeksid valmis ja siis vaatame? mulle tundub, et selline lahendus on OK, kui olen õigesti tekstist aru saanud :)

Praegu pole vaja. :) Vaatame, mis välja tuleb!

**Comment by moll** [comment]
Panin esimese redaktsiooni probleemide graafikutest https://kestame.rahvaalgatus.ee/tulemused/ lehele üles. Kombineerin ideekorje lehega siis, kui oleme kõik rahul. Puudu on lahenduste kastidel kolmnurk vms avamise märgis. Lisan selle varsti.

Tegin hetkel nii probleemide graafiku kui lahenduste tulbad ilma pealkirja pikkuse piiramiseta. Lööb küll natuke vertikaalse rütmi sassi, kuid ma ei ole veendunud, et ellips hea lahendus on. Lõpuks on probleemid ju lugemiseks. Avatud soovitusteks. Probleemide graafikul jätsin ka joonestiku ja joonlaua alt välja. Tundub see jätkuvalt vajalik?

Kui tahame lahendused loetavamaks teha --- näiteks kuvada neid nummerdatult --- peame tabelis nad teineteisest eraldama reavahe või mõne muu harvaesineva interpunktsiooniga, nagu ennist (https://github.com/rahvaalgatus/kestame/issues/13#issuecomment-434514626) kirjutasin. Praegu on lihtsalt üks mass teksti, kui mõni probleem tulbas avada. :)

**Comment by katjadanilova** [comment]
täname sind! korjasime tagasisidet ja siin ta on tervikuna:
1) tunnetatud probleemide olulisus:
- saab täitsa nii olla, aga prooviks äkki teksti veidi väiksema fondiga teha (nt 16px 18px asemel)
- pealkirja “Tunnetatud probleemide olulisus” - kirjutaks konkreetsemaks “Milliseid probleeme märgiti olulisemaks?"

2) lahendused:
a) iga pakutud lahendus võiks ikkagi olla nummerdatud, sest hetkel tõepoolest ei ole selge, kus üks algab ja teine lõpeb. Maris tegeleb faili korrigeerimisega.
b) ideedega kasti pikkus võiks olla piiratud ning kui teksti on rohkem kui see piir, siis pigem tekib scrolling bar. sest kui oletada, et ideede arv suureneb veelgi, siis kardan, et kast võib liiga pikaks saada.
c) hetkel on tulbad ja tekst paigast ära - tasub ühtlustada. 

PS meil on tekstid ka olemas, Maris täiendab neid veel tänase jooksul (need on Ideekorje.md failis).

**Comment by moll** [comment]
>  a) iga pakutud lahendus võiks ikkagi olla nummerdatud, sest hetkel tõepoolest ei ole selge, kus üks algab ja teine lõpeb. Maris tegeleb faili korrigeerimisega.

Arvan ka, et tasuks lehel iga pakutud lahendus kuvada semantiliste loendina. Nagu siin:
1. A
2. B
3. C
 
@marisjogeva, selleks peame ikkagi tagasi tulema https://github.com/rahvaalgatus/kestame/issues/13#issuecomment-434514626 teemani. Näen, et oled hetkel tabelisse pannud lahenduste ette järjekorranumbrid. Nagu hoiatasin, see ei ole kahjuks töökindel, sest mitmel lahendusel on omakorda numbrid sees. Kui tahame semantilist loendit, tuleb probleemid eraldada kas harva esineva interpunktsiooniga (semikoolon vms) _või_ eraldi ridadega, eeldusel et ükski lahendus ise ei vaja reavahet. Reavahesid saab Sheetsis vist teha shift-enteriga. Ise lisatud järkorranumbrid tuleks siis eemaldada.

>  b) ideedega kasti pikkus võiks olla piiratud ning kui teksti on rohkem kui see piir, siis pigem tekib scrolling bar. sest kui oletada, et ideede arv suureneb veelgi, siis kardan, et kast võib liiga pikaks saada.

Lauaarvutil võib muretult kerima panna. Tahvlis katsetan. Moblas ei teeks, sest seal tekkib sama häda, mis kaardiga — kerides võid lõksu jääda. 

>  c) hetkel on tulbad ja tekst paigast ära - tasub ühtlustada.

Mõtled probleemide kastide kõrgused ei ole võrdsed?

**Comment by marisjogeva** [comment]
Tahaks semantilist loendit jah. Võtsin järjekorranumbrid ära ja lisasin reavahed (cmd-enter). Vaatan nüüd lubatud tekstid üle.

**Comment by marisjogeva** [comment]
Muutsin ka md faili (Ideekorje). Puudu on lehelt sõnapilvi sissejuhatavad tekstid. Need tulevad eeldatavasti esilehelt koos piltidega üle?

**Comment by moll** [comment]
> Puudu on lehelt sõnapilvi sissejuhatavad tekstid. Need tulevad eeldatavasti esilehelt koos piltidega üle?

Jaa. Ülal lingitud `/tulemused` leht on vaid meile arutamiseks. Avalikkusele tuleb ta kenasti Ideekorjega kokku nagu soovitud.

**Comment by katjadanilova** [comment]
@moll Andri, meil oleks vaja tulemustega lehte nädala lõppuni, muidu see kaotab mõtet. On tehtav, eks?

**Comment by moll** [comment]
Tehtav! Teen ka täna ülalmainitud täiendused ära!

**Comment by moll** [comment]
@katjadanilova:
> >     c) hetkel on tulbad ja tekst paigast ära - tasub ühtlustada.

> Mõtled probleemide kastide kõrgused ei ole võrdsed?

**Comment by katjadanilova** [comment]
<img width="300" alt="screenshot 2018-11-13 16 31 39" src="https://user-images.githubusercontent.com/41726243/48419844-9e640880-e761-11e8-9fd8-c35dad142c35.png">
tekst ja esimene oranžikas tulb ei asu vertikaalselt ühel liinil

**Comment by moll** [comment]
Viisin täiendused sisse: https://kestame.rahvaalgatus.ee/tulemused/.
Kas jääb veel midagi silma, mida kohe paremaks teha?

@marisjogeva, eemaldasin ka lahenduste arvu tulba tabelist. Seda pole vaja, kuna arvu saab lahenduste tulbast kätte. 

> tunnetatud probleemide olulisus:
> saab täitsa nii olla, aga prooviks äkki teksti veidi väiksema fondiga teha (nt 16px 18px asemel)

See peakski olema 16px ehk sama suur kui tekst muudel lehtede. Kui mõtlesid, et paar pikslit väiksem font vähendab probleemide ridade arvu, siis see kahjuks ei tundu see nii olevat. Kõrgus jääb suhteliselt muutumatuks.. Võid Developer Toolsiga Firefoxis või Chrome'is proovida `<div id="#problems">` elemendi `font-size`-i paari ühiku võrra vähendada (`1.6rem` tähendab zoomimata brauseris 16px) .

**Comment by katjadanilova** [comment]
heips! võiksime lehe laivi lasta ma arvan.

infogrami kommentaari eest tänan. ma saatsin selle kujundale edasi.  

> Võid Developer Toolsiga Firefoxis või Chrome'is proovida <div id="#problems"> elemendi font-size-i paari ühiku võrra vähendada (1.6rem tähendab zoomimata brauseris 16px) .

proovisin, et 13px peal on näha erinevust, aga siis on vist tõesti tekst liiga väike. Nii et las ta olla nagu on.

**Comment by moll** [comment]
Laivis: https://kestame.rahvaalgatus.ee/ideekorje/
Kuna praegu lahtisi küsimusi ei jäänud, sulgen _issue_. Kui midagi kerkib, võime uuesti avada või uue teha. :)

**Comment by moll** [comment]
Monitoorimise skript jälgib nüüd ka probleemide tabelit. Nii arutelude kui probleemide muudatused tabelis kajastuvad hiljemalt 15 minutit peale muudatust lehel.
