### ISSUE TITLE
Avaleht ümber teha

### ISSUE THREAD

**Issue by katjadanilova** [rahvaalgatus/kestame#18]
ma arvan, et see osa jäi märkamata seal visuaali (issue#13) kommentaari juures:

hetkel tundub mõistlik niimoodi teha: veits muudame Avalehe.
Avalehele lisandub nupp "tutvu tulemustega", mis viib lehele, mis hetkel kannab nime "Ideekorje". Värv: #ff4800
[Avaleht 30 10 2018.pdf](https://github.com/rahvaalgatus/kestame/files/2584514/Avaleht.30.10.2018.pdf)

**Comment by moll** [comment]
Õigus. Jäi tõepoolest tulemuste lehe tuhinas kahe silma vahele. Tänu meelde tuletamast!

**Comment by moll** [comment]
"Kirjutan" link "Tee ettepanek veebis" tulbas viib ka tulemuste lehele. On see taotluslik?

**Comment by moll** [comment]
Lisasin ka "Tulemused" nupud esilehele. Kuidas videoga lood on? See jääb esilehelt välja?

**Comment by katjadanilova** [comment]
video võiks lisada avalehele ning samuti vahetada järjekorda: kaart jääb viimaseks ja loendur eelviimaseks. 

> Kirjutan" link "Tee ettepanek veebis" tulbas viib ka tulemuste lehele. On see taotluslik?

on, jah.

**Comment by moll** [comment]
Selge! Arvasin esialgu, et esilehe PDF pärineb vanal kujundusel, sest mäletasin, et kunagi juba videot paremale ülesse proovisime. Paistab aga, et mäletasin valesti — proovisime hoopis Eesti kaarti sinna.

Lisan kohe video ka esilehele. Kalendri lehele jääb ta alles, eks?

**Comment by moll** [comment]
Lisasin video ja liigutasin kaarti.
Hetkel jäi "Tulemused" nupp ühes "Loe Rohkem" nuppudega keskele. Kas see on okei? Nõnda jääb ta mobiilsetes seadmetes ka koos teistega. Video seevastu hüppab esimeseks.

**Comment by katjadanilova** [comment]
aitäh! näeb hea välja! 

> Hetkel jäi "Tulemused" nupp ühes "Loe Rohkem" nuppudega keskele. Kas see on okei?

on OK!

> Lisan kohe video ka esilehele. Kalendri lehele jääb ta alles, eks?

jah!
