### ISSUE TITLE
Tekstid .md kujule ja eraldi kausta praeguse seisuga

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/kestame#2]
Praegune seis:
https://docs.google.com/document/d/1DnsO_2-AjN8vjGUkJy4FumlTotGmuzlmN4ZmwG_SXC4/edit 

Md failide kaust:
https://drive.google.com/drive/u/0/folders/17AUpPMiJWnT9I-MAld5j_1wa1O-2cNAa

**Comment by moll** [comment]
Esialgsed tekstid liigutasin kausta. "Probleemist" leht veel lõpetamata, kuid käsitleme seda edasi https://github.com/rahvaalgatus/kestame/issues/10 osana.

**Comment by katjadanilova** [comment]
@moll Hei! Uuendasime .md faili "Algatusest". Palun laivi lasta.

**Comment by moll** [comment]
Tehtud!

**Comment by katjadanilova** [comment]
@moll uuendasime "Probleemist" lehte. Palun laivi lasta.
NB vahetasime ka lehe pealkirja (Probleemistik Probleemist asemele) - palun vaata, kas parandasin õigetes kohtades?

**Comment by moll** [comment]
Up. Tahad pealkirja menüüs ka muuta?

**Comment by katjadanilova** [comment]
jah! tahaks küll :)

**Comment by moll** [comment]
Ka tehtud. Kas mitte vahepeal ei olnud lehe nimi "Probleemistik" juba? Meenuks nagu.

**Comment by katjadanilova** [comment]
@moll 
- [ ] muutsin "Kalender" lehe tekstid. palun uuendada. 

- [ ] palun panna alamlehe uueks pealkirjaks "Arutelud".

**Comment by moll** [comment]
Kalender lehe pealkirjaks "Arutelud"? Aadressiks ka siis (vanalt suunamisega, loomulikult), eks?

**Comment by katjadanilova** [comment]
> Kalender lehe pealkirjaks "Arutelud"? Aadressiks ka siis (vanalt suunamisega, loomulikult), eks?

mõlemale jah :)
