### ISSUE TITLE
Tulemuste uuendusi ei kuvatata veebilehel

### ISSUE THREAD

**Issue by katjadanilova** [rahvaalgatus/kestame#20]
vaata palun - eile öösel uuendas Maris tulemuste tabeli, aga veebilehele ei ole nad teed leidnud.

**Comment by moll** [comment]
Andestust! Toimetasin arvutiga, mis selle eest vastutas, ja monitoorija jäi pärast käivitamata. Lülitasin ta mõned tunnid tagasi taas sisse.
