### ISSUE TITLE
19.11 seisuga sõnapilved

### ISSUE THREAD

**Issue by n2nsim** [rahvaalgatus/kestame#21]
![parem-ee-sonapilv-hirmud_19 11](https://user-images.githubusercontent.com/45167261/48702016-7e689500-ebf8-11e8-9d13-ee7cd583478e.png)
![parem-ee-sonapilv-lootused_19 11](https://user-images.githubusercontent.com/45167261/48702017-7f012b80-ebf8-11e8-8c0b-9bf3d26787d3.png)

**Comment by moll** [comment]
Up @ https://kestame.rahvaalgatus.ee/tulemused/.
