### ISSUE TITLE
deadline: 25.11 Lisada nupp ankeediga Tulemused lehele

### ISSUE THREAD

**Issue by katjadanilova** [rahvaalgatus/kestame#22]
palun lisa nüüd see nupp, millest me rääkisime. 
Tulemused lehele, esimese paragrahvi lõppu pealkirjaga "Esita oma idee". Nupp võiks olla meie tavapärane sinine. 
ankeedi ma sinuga jagasin, aga siin on ka link sellele, sest selle ei pea lehele embeddima: https://goo.gl/forms/aJs0yQAbZWPm4Eo42 

Maris uuendab tänase päeva jooksul selle paragrahvi teksti ka, nii et selle on vaja homme ka uuendada.

**Comment by moll** [comment]
Nupu lisan kohe, eks, mitte 25ndal?

**Comment by katjadanilova** [comment]
väljendasin vist ennast segaselt. 
ei-ei, 25ndal. ankeet ise on ametlikult alates 26ndast avatud.

**Comment by moll** [comment]
Oki! Pühapäeva õhtul siis! :)

**Comment by moll** [comment]
Nupp üleval.

Kas Markdownis kirjutatud pealkiri "Mis teeb enam muret?" on mõeldud ka asendama probleemigraafiku pealkirja? Kindel, et sõna "enim" sinna ei mõelnud panna, @marisjogeva?

**Comment by marisjogeva** [comment]
Jah. Tahtsin sõna “probleem” kordusi tekstis vähemaks saada. Enim on õige, aitäh märkamast!

Maris

**Comment by moll** [comment]
Eeldan, et kõik praeguseks sobis. :) Panen seniks _issue_ kinni, kuniks midagi taas kerkib.

**Comment by marisjogeva** [comment]
Hei!

Kõik sobis ideaalselt. Aitäh! 
Sätime täna veel tulemuste lõpud veebi ning anname Katjaga teada, kuidas veeb mõneks ajaks nö seisule panna, kuni tulemustega tööd teeme. 

tervitades
Maris
