### ISSUE TITLE
Uuendada avaleht

### ISSUE THREAD

**Issue by katjadanilova** [rahvaalgatus/kestame#23]
kuna meil esmaspäevaga lõpeb ideede korje, sooviksime teha muudatused, mis kestavad paar kuud.
muudatused on lihtsad. üks neist on avalehe muudatus (plokkide ümbertõstmine). 

Tore oleks, et 17.12 see oleks juba valmis, aga kuna me pole sellest varem kokku leppinud, palun ütle mida sinu graafik lubab. 

[Avaleht 14 12 2018.pdf](https://github.com/rahvaalgatus/kestame/files/2679774/Avaleht.14.12.2018.pdf)

tekste muudab Maris täna.

**Comment by moll** [comment]
Pole probleemi. Teen esmaspäevaks ära!
"Vaatan tagasisidet" viib Tulemuste lehele?

**Comment by katjadanilova** [comment]
aitäh! 

> "Vaatan tagasisidet" viib Tulemuste lehele?

jah!

**Comment by moll** [comment]
Värskendatud avaleht üleval!

Eeldasin, et XXX-id "Algatuses sai igaüks osaleda..." sektsioonis tähistasid andmetest tuletatud numbreid. Asendasin nad seega arutelude tabeli ridade, osalenud inimeste ja ideede arvudega. Kui see polnud taotluslik, andke teada. Osalenud 300 asemele ilmus nüüd hoopis 264, sest nii palju arutelude tabeli tulpadest kokku tuli. :)

Kuhu "Loe rohkem" lingid all viima pidid? Esimene ilmselt "arutelude" lehele, aga teised kaks? Tulemuste lehele?

Asedasin kolm "Vaata tagasisidet" linki lõpus aga ühe nupuga. Oli hetkel pisut kergem lahendus ja haakus tibake paremini ülejäänud lehega. :innocent:

**Comment by moll** [comment]
Ahjaa, kuna meil tabelis veebi ja mitte-veebi ideede jaoks märget pole, asendasin teksti üldisema lausega. Kui teate täpselt veebi ideede arvu, võib selle tagasi panna.

**Comment by marisjogeva** [comment]
@moll mul on kolm arutelu, mis ei olnud registreeritud ja sellest ka osaliselt erinevused. Lisasin need arutelud registreerimisankeedi skriptiallikale ja sain numbrid klappima (341 osalejat!). Arutelusid peaks saama 32, aga millest tuleb automaatselt loendisse 165 ideed, ma ei mõista. Kui lugesin veebis joonisel kuvatud numbrid kokku sain 90?  Hea kui saame numbrid jonksu, siis saab nendest ka rääkida.

**Comment by moll** [comment]
Minu viga. Esilehe number oligi valesti arvutatud. Parandasin! :)

Küll aga hetkel on kolmel viimasel arutelul puudu asukoht ja skript ootab sellega taga, et need laivi saata. :) Eeldan, et neil üldse oli asukoht.

**Comment by marisjogeva** [comment]
Neil oli asukoht, aga tegemist oli meetodikoolitusega. Ankeedis muideks pakkusime, et kui ei soovi arutelu/kontakte avalikustada, siis anna sellest teada ja võtame eraldi ühendust. Kas ma nii saaksin need arutelud jätta, et annan neile pealkirjad ning määran asukohana Tallinna, kuid võtame arutelujuhi kontaktid ära?

**Comment by moll** [comment]
Võid. Võid neile kas panna suvalised Tallinna koordinaadid või kui ei õnnestu, võin koordinaatideta arutelud kaardilt peita. Hetkel ootab leht igalt arutelult asukohta.

**Comment by moll** [comment]
Nägin, et olidki vahepeal lisanud kontaktideta arutelud. Tegin kindlaks, et nende puhul "Korraldaja" rida ei kuvata. Eelnevalt olid need vist kahe tühja komaga.

Muidu aga järeldan vaikusest, et kõik senine on sobinud ning võib _issue_ sulgeda. :)
