### ISSUE TITLE
Tagasiside viited esilehel

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/kestame#26]
@marisjogeva:
> Andri, ole hea ning muuda avalehe lõpus lahenduste tulpade juures olev nupp “vaata tagasisidet” kolmeks samasuguseks nupuks. Iga teema all peaks olema võimalik  avada tagasisidefail. Esimene on olemas, kuid palusin Nänsil sellesse veel ühe paranduse teha. Nii et homme saaks juba ka nuppudele sisu taha panna.

Kuhu need nupud viima peaks? Faili? Nt mingisse PDFi? Üks PDF/dokument per probleemi valdkond?

**Comment by marisjogeva** [comment]
Täpselt! Iga teema/tulba kohta tuleb ilus pdf. Kokku kolm. Nänsi pakkus, et parem oleks kui pdf-i asemel oleks veebilehed, aga kunagi ammu otsustasime Katjaga, et jääme kõige lihtsama lahenduse juurde. Kas Sulle näib loogiline?

Maris

**Comment by moll** [comment]
PDFid on okeid, kuigi eks näis, kas kolm "Vaata tagasisidet" nuppu külastajatele selged on. Jään PDFide ootele igal juhul.

**Comment by moll** [comment]
Kuna tundub, et "Sõelutud ettepanekud" sektsioon saab natkue teistlaadi kuju kui lihtalt kolm PDFi linki, siis käsitleme seda https://github.com/rahvaalgatus/kestame/issues/27 _issue_-s edasi.
