### ISSUE TITLE
Sõelutud ettepanekud

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/kestame#27]
Nänsi:
> ESILEHT – Lahendused probleemide kaupa:
> - Selle osa võib esilehelt maha võtta (“Tulemused” alalehele jääb see alles)
> - Selle osa asemele peaks aga tulema täiesti uus osa, hetkel paneme nimeks “Sõelutud ettepanekud” (vajadusel hiljem muudame)
>
> Uus osa – Sõelutud ettepanekud
> - Seda tuleb kuvada esilehel ja „Tulemused“ alamlehel kõige viimasena, st „Lahendused probleemide kaupa“ all
> - Sisuliselt peaks see väga sarnane välja nägema „Lahendused probleemide kaupa“ skeemile, ent üks kategooria on rohkem: Sündimus (tähtistav värv on oranž hex #ff4800), Eesti-sisene ränne (hall #808284), Piiriülene ränne (helehall #a7a9ab), Tööhõive (roheline #65a580) – vt näidis allpool
> - Igal peakategoorial on kolm alamkategooriat: Riigile, Kohalikele omavalitsustele, (Ideed) kogukondadele. Alamkategooriate värvid on vastavalt ülemkategooria värvidele, neid värvilisemaks muutma ei hakka. Ehk Sündimuse alamkategooriad on oranžid, Tööhõive omad rohelised jne.
> - Rippmenüüsse lähevad antud teemasse sobivad ettepanekud, ettepaneku peale klikates tuleb lahti sellekohane probleem + lühikirjeldus. Materjali saadan peatselt järele.
> - Kogu selle krempli lõppu peaks iga teema alla tulema sinine nupuke „Kõik ettepanekud“
>
> <img width="801" alt="soelutud ettepanekud" src="https://user-images.githubusercontent.com/156837/53725824-abb61780-3e64-11e9-8c3c-bf627cbba446.png">

**Comment by moll** [comment]
Mobiilidel kasutamiseks ka nägemus? Olen kahevahel, kas _tabid_ (neli kategooriat ülal) kuvada _dropdown_ina või lihtsalt nelja kategooria tulbad üksteise järel (12 sektsiooni kokku). Kardan, et _dropdown_iga juhtub see, et kerides "Kogukondadele" tulbani on kõigil moblakasutajatel juba meelest läinud, et eksisteerisid kolm teist kategooriat ka ja nende valimiseks tuleks taas üles liikuda.  

> Materjali saadan peatselt järele.

Mis kujul sisu mõtlede hoida? Google Spreadsheetis nagu muu info? Vaataks korra vormi üle, et see oleks nii masinloetav saidile kui ka muutmiseks mugav teile.

**Comment by n2nsim** [comment]
"Kõik ettepanekud" nupukeste jaoks PDF failid, seal on Eesti-sisene ja piirideülene ränne koos.
[Ränne_ettepanekud.pdf](https://github.com/rahvaalgatus/kestame/files/2930005/Ranne_ettepanekud.pdf)

[Sündimus_ettepanekud.pdf](https://github.com/rahvaalgatus/kestame/files/2930006/Sundimus_ettepanekud.pdf)

[Tööhõive_ettepanekud.pdf](https://github.com/rahvaalgatus/kestame/files/2930007/Toohoive_ettepanekud.pdf)

**Comment by n2nsim** [comment]
> Mobiilidel kasutamiseks ka nägemus? Olen kahevahel, kas _tabid_ (neli kategooriat ülal) kuvada _dropdown_ina või lihtsalt nelja kategooria tulbad üksteise järel (12 sektsiooni kokku). Kardan, et _dropdown_iga juhtub see, et kerides "Kogukondadele" tulbani on kõigil moblakasutajatel juba meelest läinud, et eksisteerisid kolm teist kategooriat ka ja nende valimiseks tuleks taas üles liikuda.
> 
> > Materjali saadan peatselt järele.
> 
> Mis kujul sisu mõtlede hoida? Google Spreadsheetis nagu muu info? Vaataks korra vormi üle, et see oleks nii masinloetav saidile kui ka muutmiseks mugav teile.

Jah, kogu info siin, need osad on markeeritud "Ettepanek" ja "Lühike tagasiside": https://docs.google.com/spreadsheets/d/1XoCctpGEQuAHiv_px7-Z-R9Q_9U4T88NEN0yspkf3os/edit?usp=sharing. Fail on veel muutumises tänase õhtuni.

Mobiilis kasutamiseks ei ole nägemust hetkel. Kas nii ei toimiks, kui sündimuse, tööhõive jms teemad oleksid I drop-down, sealt edasi klikkides tuleks sihtrühmade drop-downid ja seejärel saab juba ettepanekuid-tagasisidet scrollida.

**Comment by n2nsim** [comment]
Reply @moll kommentaarile e-mailis, mis puudutab "Kokkuvõte ja edasised sammud" osa.
Su pakutu on igati mõistetav, kas ma saan õigesti aru, et saad selle osa siis ise n-ö ära teha?
Selle sisendinfo koguneb samuti siia, esmased sammud on tehtud, aga see protsess on veel toimumises ja pole lukku löödud: https://docs.google.com/spreadsheets/d/1XoCctpGEQuAHiv_px7-Z-R9Q_9U4T88NEN0yspkf3os/edit.

**Comment by moll** [comment]
Süvenen varsti kirjutatusse, kuid mulle tundub, et ülemine link lubab kõigil faili muuta. Kuna GitHubi arutelu on siiski avalik, soovitan igaks juhuks muutmisõigus avalikkuselt ära võtta. ;)

**Comment by n2nsim** [comment]
Uus teadmine mulle. Võtsin link-share'i maha, palun jaga minuga enda e-maili, millega GD kasutad.

**Comment by moll** [comment]
Kas andri@dot.ee-le õiguse jagamine töötab?

**Comment by n2nsim** [comment]
@moll - kas said failile ligipääsu? Kas vajad veel mingit sisendinfot? Millises ajaraamis sa tööle plaanid hakata?

**Comment by moll** [comment]
> kas said failile ligipääsu?

Sain ligipääsu, aitäh!

> Kas vajad veel mingit sisendinfot?

Saan õigesti aru, et sõelutud ettepanekute sektsiooni andmed peaksid tulema tabelist "Ettepanekute kokkuvõte"? Kui nii, siis kohendan seda natuke masinloetavamaks — ehk viin kategooria iga rea juurde ja lisan tulpadele pealkirjad. Küll aga on pisut segane, kuidas ettepanekute read alamkategooriate (riigile, omavalitsustele, kogukondadele) vahel jaotuvad? Esialgu jäi mulje, et iga ettepanek on ühes kolmest alamkategoorias. "Ettepanekute kokkuvõtte" tabelis aga tundub, et igal ettepanekul/probleemil on lahendus omavalitsuse ja kogukonna tasemel.

> Millises ajaraamis sa tööle plaanid hakata?

Sihtisin ühele lähipäevale — tänasele, homsele või nädalavahetusele. Haakub see te plaanidega? Enne laivi lükkamist kindlasti näitan, kas sõelutud ettepanekute lahendus sobib.

**Comment by moll** [comment]
^ @n2nsim. ;)

**Comment by n2nsim** [comment]
Seda oskab kommenteerida Maris, aga ma ei saa teda mingil põhjusel siin tagida. Seega saadan talle siinse meili peale.

**Comment by n2nsim** [comment]
@moll Marise tagasiside: 
Tabel on ehitatud üles selliselt, et on ettepanekud (riik, kov, kogukond) on kolmes eraldi veerus.
- riigi tasandi ettepanekutele on lisaks sõnastatud probleem (mocupil näha, kuidas see peaks jääma) ning ka #väljund (mis näitab kuhu in ettepanek suunatud. KOV ja kogukond tasandi loetelud on lihtsalt nimekirjana.
- riik-KOV-kogukond veerud ei ole omavahel seotud, kuigi osad ettepanekud on sarnased (pidimegi vaatama, kuidas see töötab).

**Comment by moll** [comment]
Jäi eile tänamata info eest! Jätan nad hetkel's kolme tulpa — see ei tohiks nende masinloetavust häirida. Pisut aga tabelit kohendan. Võtan selle täna õhtul ja homme hommikul ette.

> Seda oskab kommenteerida Maris, aga ma ei saa teda mingil põhjusel siin tagida. Seega saadan talle siinse meili peale.

Testime:  @marisjogeva :) 

> #väljund (mis näitab kuhu in ettepanek suunatud. KOV ja kogukond tasandi loetelud on lihtsalt nimekirjana.

Mockupis olete lisanud nii "Edasi suunatud" sihtpunkti kui ka värvinud fraasi peale trelle (nt "#Laste ja perede arengukava) siniseks. Kas sihtpunkti veebiaadress oli plaanis hilisemas faasis tabelisse kuskile tulpa lisada?

**Comment by marisjogeva** [comment]
Tere!

Sihtpunkti oleks hea linkida küll, kuid võimalusel lisaks lingid hiljem (nt kui on arengukava koostamise leht olemas, või kui rahvaalgatus on päriselt üles läinud). Kas link peaks olema tabelis eraldi või piisab viite (nt #rahvaalgatusveeb) linkimisest tabelis, oskad vast öelda?

tervitades
Maris

**Comment by moll** [comment]
> Kas link peaks olema tabelis eraldi või piisab viite (nt #rahvaalgatusveeb) linkimisest tabelis, oskad vast öelda? 

Eraldi tulbas oleks parem. Esiteks seepärast, et tundub, et hüperlinke CSV-eksport ei toeta ning teiseks, tundub, et Google Spreadsheets ei luba üksikuid teksti sõnu niikuinii linkida — pead terve välja lingiks tegema. Siis tasuks juba kindluse mõttes _silt_ (`#rahvaalgatusveeb`) ka teksti välja tuua. 

Kolme tulba lahendus tundub tasapisi kahtlaseks muutuvat. Kindel, et omavalitsuse jt grupid ei saa kunagi probleemikirjeldusi, silte/sihtkohti ega linke? Kui saavad, tasuks meil tulpadest read teha ja lisada üks tulp "grupi" tuvastuseks (riik, omavalitsus jne).

**Comment by marisjogeva** [comment]
Eraldi veerg on muidu ok, aga kas sobib ka nii, et mõni #väljund jääb linkimata?
Räägin jätkuvalt ettepanekute väljundeid läbi ning mõned nendest veel muutuvad (see keeruline valitsuse moodustamise aeg ka paralleelselt…), nii et mõne ettepaneku taha võib jääda ministeeriumi nimetus. Seda linkida oleks absurdne. 

Omavalitsustele ja kogukondadele mõeldud ideedele võin probleemid juurde tekitada, kuid mu hinnangul see ei annaks juurde. KOVid-kogukonnad on erinevad ning iga teemat saavad nad oma nurga alt vaadata. Ka sihtkohad/lingid on igal omavalitsusel/kogukonnal erinevad (kogukondades sõltubki eelkõige kohalikust initsiatiivist). Kas need veerud jäävad sedamoodi liiga ebaühtlased? Kui jätame ka riigi tasandi ettepanekutele probleemi osa kuvamata?

terv
Maris

**Comment by moll** [comment]
> Eraldi veerg on muidu ok, aga kas sobib ka nii, et mõni #väljund jääb linkimata?

Sobib ikka. Võime ka nii teha, et väljundi nimi ja link mõlemad on eraldi tulpades. Kui linki pole, jääb lihtsalt väljund sellise stiiliga nagu soovid. Kui jätad väljundi teksti sisse, võime jätta eraldi stiilimata.

> Omavalitsustele ja kogukondadele mõeldud ideedele võin probleemid juurde tekitada, kuid mu hinnangul see ei annaks juurde.

Seda ei ole minu pärast vaja. Kui iga ettepanek eraldi real hoida, võid tulpi tühjaks ka jätta. Praegu on ju tegelikult sama — "probleem" on vaid riigiga seonduval ettepanekul.

> Ka sihtkohad/lingid on igal omavalitsusel/kogukonnal erinevad (kogukondades sõltubki eelkõige kohalikust initsiatiivist). Kas need veerud jäävad sedamoodi liiga ebaühtlased? Kui jätame ka riigi tasandi ettepanekutele probleemi osa kuvamata? 

Kui tahad omavalitsuse ja kogukondade ettepanekutele ka sihtkohti, siis tasuks tõesti kõik eraldi ridadele viia ja vastavalt vajadusele siis probleemi tulp täita (praeguse põhjal ainult riigi ridade jaoks). Teed seda ise võin "reastan" ise? :)

**Comment by moll** [comment]
> Kui jätad väljundi teksti sisse, võime jätta eraldi stiilimata.

Selle all mõtlesin väljundi jätmist ettepaneku teksti sisse.

**Comment by marisjogeva** [comment]
See tähendab siis ilma eraldi veeruta? Ja siis ka linkimata?
M.

**Comment by moll** [comment]
> See tähendab siis ilma eraldi veeruta? Ja siis ka linkimata?

Ettepanekuga ühes ei saa linkimist ega eraldi stiilimist, jap.

**Comment by moll** [comment]
Tegin praeguse põhjal säherduselt: https://kestame.rahvaalgatus.ee/lahendused/. Läheb sinna suunda, mida ette kujutasite?

Kui tahame sõna "Probleem:" nt eraldi reale ja nt rasvaselt, tasuks ta kõigepealt tabelist eemaldada ("find & replace" aitab :) ja's lisan lehele.

Sildi/suunamise linkimise teemal juba rääkisime.

**Comment by moll** [comment]
(Mobiilivaadet vaja natuke veel kohendada, sellele ei tasu veel tähelepanu pöörata)

**Comment by moll** [comment]
@n2nsim: Kas mahedamat/pastelsemat oraži teil poleks tulpade taustaks? Praegune tiba kriiskab ja pole kontrasti tõttu eriti mugav pikemaks lugemiseks.

**Comment by n2nsim** [comment]
selline on, aga kardan, et valge tekst ei jää siis väga hea. katseta ja anna teada: #ffca9f

**Comment by moll** [comment]
Valge kindlasti nähtav ei jää, aga mustaga selline:
![Screenshot from 2019-03-25 22-54-00](https://user-images.githubusercontent.com/156837/54959417-f0f3d380-4f50-11e9-802a-68ee523b54c7.png)

Miski muu toon ehk? Kust see oranž välja tuli? See teie grupi silmadele loetav?

@marisjogeva: Mida sõelutud ettepanekutega ette võtame's? Mobiiliversioon kõrvale jättes, mis veel teha vaja oleks? Sisu ei pea minu pärast lõplik olema — seda saab sekundiga tabeli põhjal uuendada — aga struktuur paigas? Sihtpunkte KOVi ja kogukondade ettepanekute põhjal automaatselt ei loe ja see jääb vaid riigi ettepanekute kohta?

**Comment by marisjogeva** [comment]
Ettepanekute struktuur on paigas ning peaaegu kõigil on ka viited olemas (va mõni üksik + rahvaalgatused, mis ei ole veel rahvaalgatuseks saanud). Kui neid saab jooksvalt tabeli kaudu uuendada, siis võiks mu arvates asap töösse panna.

**Comment by moll** [comment]
Sõelutud ettepanekud laivis! Nii [esilehel](https://kestame.rahvaalgatus.ee/) kui ka [tulemuste](https://kestame.rahvaalgatus.ee/tulemused/) lehel. Otsustasin hetkel mobiilile kõik neli kategooriat korraga välja kuvada, sest üles-alla kerida on lihtsam ja selgem kui kategooriate vahetuse lahendused.

Läks laivi viimase tabeli sisuga. Kui uuendad ja soovid värskendust laivis näha, anna lihtsalt kuidagi teada, @marisjogeva. ;)

**Comment by marisjogeva** [comment]
Paneks viimaste tulpade pealkirjaks “Ettepanekud”, siis eristub “lahendustest”. Proovin enne homset vaheteksti ka kirjutada ja lisan tabelisse mõned nimed. Annan teada kui võiks uuendada.

**Comment by moll** [comment]
Ümbernimetatud.

**Comment by marisjogeva** [comment]
Kirjutasin mdi faili (tulemused) ühe vaheteksti. 
Aga võib-olla oodata uuendamist õhtuni, kui jõuan korra uuesti veel ka ettepanekute tabeli üle käia uuema infoga. 

M.

**Comment by marisjogeva** [comment]
Käisin üle. Kõigil ettepanekutel on nüüd viited. Arvan, et ca nädala pärast on võimalik veel täpsustus ja siis saab teha staatiliseks. 
tervitades
Maris

**Comment by moll** [comment]
> Käisin üle. Kõigil ettepanekutel on nüüd viited. Arvan, et ca nädala pärast on võimalik veel täpsustus ja siis saab teha staatiliseks.

Värske sisu laivis.
