### ISSUE TITLE
"Mida igaüks saaks ise ära teha?" sektsioon

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/kestame#28]
Nänsi:
> Uus osa – Mida igaüks saaks ise ära teha?
>
> - Et sündimus tõuseks.
> - Et tööhõive paraneks.
> - Et ränne oleks tasakaalus.
>
> Juurde tuleb visuaal, mis digitaliseeritakse.
> See osa võiks minna „Tulemused“ lehel „Sõelutud ettepanekud“ alla.
> 
> <img width="667" alt="visuaal on board" src="https://user-images.githubusercontent.com/156837/53726463-e53b5280-3e65-11e9-86a4-b7a19ab47a24.png">

**Comment by moll** [comment]
Digitaliseeritakse ehk tehakse vektorformaati? SVG-ks? Või millekski interaktiivseks?

**Comment by moll** [comment]
@n2nsim, @marisjogeva, olete sellega ka kuskile vahepeal jõudnud?

**Comment by n2nsim** [comment]
@moll Uurin Teelelt selle visuaali kohta

**Comment by moll** [comment]
Järeldan, et see visuaal jääb mängust välja. :) Kui kunagi soov taas kerkib, andke aga teada! Panen seniks _issue_ kinni.

**Comment by marisjogeva** [comment]
Aitäh! 
Mõte on veel olemas, kuid praegu muude asjade tõttu teostus ootel. 

M.
