### ISSUE TITLE
"Kokkuvõtte ja edasiste sammude" sektsioon

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/kestame#29]
@n2nsim:
> Seda veel otseselt teostama ei saa hakata. Küll aga võiksime mõelda parima lahenduse peale. Vaja on visuaali, mis näitab, kuhu mitu ettepanekud on edasi suunatud (näide allpool kohe). Siin on nüüd küsimus, et kas teen faili ise valmis, mille saab lihtsalt üles laadida või on sul endal mingi mõte, kuidas seda teha?
> 
> See asi võiks olla nähtav esilehel pärast „Sõelutud ettepanekud“ osa ja „Tulemused“ lehel kõige viimasena pärast „Mida igaüks saaks ise ära teha?“ osa.
>
> ![edasised sammud checkboxes](https://user-images.githubusercontent.com/156837/53945705-11e7a800-40ba-11e9-81ad-f1abebdca3ab.png)

@moll:
> "Kokkuvõtte ja edasiste sammude" osas aga soov näidata lihtsalt u 5 pildikest seletava teksti ja numbriga? See on kergelt tehtav. Ma soovitaks küll teksti iga ikooni alla viia. Nõnda pole legendi vaja ega põhjusta värvid värvipimedatele probleeme.

@n2nsim (https://github.com/rahvaalgatus/kestame/issues/27#issuecomment-469596416):
> Reply @moll kommentaarile e-mailis, mis puudutab "Kokkuvõte ja edasised sammud" osa.
Su pakutu on igati mõistetav, kas ma saan õigesti aru, et saad selle osa siis ise n-ö ära teha?
Selle sisendinfo koguneb samuti siia, esmased sammud on tehtud, aga see protsess on veel toimumises ja pole lukku löödud: https://docs.google.com/spreadsheets/d/1XoCctpGEQuAHiv_px7-Z-R9Q_9U4T88NEN0yspkf3os/edit.

**Comment by moll** [comment]
Ikooni või visuaali osas võid ise otsustada, @n2nsim. Mõne tabeli põhjal aga ettepanekute arv kokku lugeda on lihtne. Mis kujul te neid andmeid hoida mõtlesite? Samasse "Ettepanekute kokuvõte" tabelisse uus tulp infoga, kas ettepanek läks Rahvaalgatusse, arengukavasse või mujale?

**Comment by n2nsim** [comment]
Need andmed on selles tabelis:

<img width="1426" alt="screenshot 2019-03-07 at 14 55 25" src="https://user-images.githubusercontent.com/45167261/53958220-1f685680-40e9-11e9-9317-a22befbdaf51.png">

**Comment by moll** [comment]
Mõtled kõigis neljas "- Süntees"-i tabelis? Need, või vähemalt see tulp, tuleks teha siis masinloetavaks. Masinloetav tähendab, et lepime kokku, millised sõnad on tulbas lubatud ja kas neid on alati üks või võib üks ettepanek ka mitmesse kohta jõuda. Siis vaatame üle, et kõik neli tabelit oleksid identsete ja samapealkirjaliste tulpadega ja ei sisaldaks ülearuseid ridu või tühjasid ridu.

Kui see tundub tülikas, ei pea me sihtpunktide lugemist automatiseerima. Paneme kuskile käsitsi kirja, mitu ettepanekut kuhu läks ja kogu lugu. :)

**Comment by moll** [comment]
@n2nsim, @marisjogeva, kui eelistame automaatselt ettepanekud sihtpunktide alusel kokku lugeda, siis tasuks kokkuvõtte tabelisse tõesti eraldi sihtpunkti tulp lisada ning iga ettepanek eraldi reale viia, nagu Marisega https://github.com/rahvaalgatus/kestame/issues/27 _issue_-s rääkisime.

**Comment by marisjogeva** [comment]
Sa mõtled seda google spreadsheeti tabelit, eksju? Prooviks. Kas teed ise? Teiseks küsin sellist asja, et kas ühele ettepanekule võin jätta ka kaks sihtpunkti? Arutasime korra Teelega, et mõnele ettepanekule võiks selline lahendus sobida. Paneksime sihtpunktidena kirja ka mõned katusorganisatsioonid, kes ettepaneku enda hoolde võtavad, kuid kes rahvaalgatuseks ainest ei näe. 

terv
Maris

**Comment by moll** [comment]
> Sa mõtled seda google spreadsheeti tabelit, eksju? Prooviks. Kas teed ise? 

Võin tulba ja näidise valmis teha küll. Kas viin siis ka "Riik+omavalitsus+kogukond" tulpade asemel kõik eraldi ridadele? Siis saad vajadusel omavalitsuse ja kogukonna ettepanekutele ka sihtpunkte lisada.

> Arutasime korra Teelega, et mõnele ettepanekule võiks selline lahendus sobida. Paneksime sihtpunktidena kirja ka mõned katusorganisatsioonid, kes ettepaneku enda hoolde võtavad, kuid kes rahvaalgatuseks ainest ei näe. 

Võid ikka. Aga lepime's kokku mingi mustri, kuidas linke ja nende nimesid ühes väljas struktureerida. Kuidas oleks "nimi", koolon, tühik ja link? Erinevad lingid on reavahega eraldatud. A la

```
Rahvaalgatus: https://rahvaalgatus.ee/initiatives/....
Katusepakkujate OÜ: https://example.com 
```

**Comment by moll** [comment]
Ja kui linki pole, võid lihtsalt eraldi ridadele sihtpunktid lisada:

```
Rahvaalgatus: https://rahvaalgatus.ee/initiatives/....
Uustulnukate korteriühistu
```

**Comment by moll** [comment]
Edasiste sammude statistikaks saab siis lihtsalt linkide väljast nimed kokku lugeda ja kas kõik või vaid valitud kuskil kuvada, kui säherdusi ühekordseid sihtpunkte (nagu mu näited ülal) tahta ignoreerida.

**Comment by marisjogeva** [comment]
Oot, aga ega see tähenda kogu tabeli ümber tegemist? Ma liiga kategoorilisi muutusi enam ette ei võtaks:)

Teiseks tuli mul meelde, et puudu on veel vahetekstid (enne mõlemat joonist selgitaksin, kuidas need kokku on saanud), mille saadaksin sulle asap, aga küsin, kas on pikkuse piiranguid? 

Ega sa ole saanud tegeleda nende tagasiside failidega, mille Nänsi saatis. Kui need üleval, saaksin aruteludes osalenutele jagada (kuigi nüüd on vist juba mõistlik kogu info ettepanekute tuleviku ja saatuse kohta korraga välja panna).

**Comment by moll** [comment]
> Oot, aga ega see tähenda kogu tabeli ümber tegemist? Ma liiga kategoorilisi muutusi enam ette ei võtaks:)

"Ettepanekute kokkuvõte" tabelist räägime ikka, eks? Sõltub, mida me teha tahame. Kui tahame sihtpunktid eraldi tekstist välja tuua ja kuskile linkida, peame selle info kuidagi muust proosast välja tooma. Kui tahame sihtpunktid automaatselt kokku lugeda, siis tuleb ka kokku leppida, mis formaadis nad on. :)

> Teiseks tuli mul meelde, et puudu on veel vahetekstid (enne mõlemat joonist selgitaksin, kuidas need kokku on saanud), mille saadaksin sulle asap, aga küsin, kas on pikkuse piiranguid?

Ei ole piiranguid. Kirjuta kui pikalt ja uhkelt soovid — võid teha ka Google Drive'i "kestame md failide" kausta uue Markdown faili ja. Lõpuks kuskile sinna nad niikuinii lähevad. Jooniste all mõtled käesolevat _issue_-t ja https://github.com/rahvaalgatus/kestame/issues/28 visuaali? Tekstidega mul kiiret ei ole, sest pole ju ka veel jooniseid. :P

> Ega sa ole saanud tegeleda nende tagasiside failidega, mille Nänsi saatis. Kui need üleval, saaksin aruteludes osalenutele jagada (kuigi nüüd on vist juba mõistlik kogu info ettepanekute tuleviku ja saatuse kohta korraga välja panna).

Mõtled kolme PDFi, mis ta https://github.com/rahvaalgatus/kestame/issues/27#issuecomment-469593309 kommentaari üles laadis? Tahaksid, et lükkan need Kestame lehele enne https://github.com/rahvaalgatus/kestame/issues/27 valmimist üles, et saaksid linke jagada? Vabalt.

**Comment by moll** [comment]
@marisjogeva, lihtsalt infoks, et olen hetkel ülemise kommentaari ja teiste lahtiolevate _issue_-de tagasiside ootel. ;)

**Comment by marisjogeva** [comment]
Vabandust: 
1) tahaks sihtpunkte linkida nii palju kui võimalik ja see oleks ka hea, kui samas tekiks ka loendur. Täitsin tabelit hetkel nii palju kui sain, aga mul tekkis paar küsimust ka: 
 - kas sihtpunkti nimetus peaks olema sama mis #nimetus? Nt: kasutaks viiteid nagu #lastejaperedeprogramm, #Eesti2035. Küsimus on, et kas viite veerus peaks jääma samasuguse nimevormi juurde?
 - kui mul on ühel nimetusel kaks sihtpunkti, siis lisan need üksteise alla?
KOV ja kogukonna ettepanekutele sihtpunkte ei teeks - kõik ettepanekud lähevad ühtmoodi kohalikele omavalitsustele ja linnade/valdade liidule. Nii võib vast tabel sellisel kujul jääda, kuid kas loenduri tarbeks oleks vaja viited ka KOV ettepanekutele lisada?
2. Peaksime uued joonised ja tekstid lisama lehele "Tulemused", teen ikka uue faili?
3. Mõtlesin jah:)

**Comment by moll** [comment]
> kas sihtpunkti nimetus peaks olema sama mis #nimetus? Nt: kasutaks viiteid nagu #lastejaperedeprogramm, #Eesti2035. Küsimus on, et kas viite veerus peaks jääma samasuguse nimevormi juurde?

Minu pärast võid trellid panemata jätta ja laseme arvutil need lehte genereerides lisada. Sa ei peaks sihtpunkte seletusse ka lisama, sest need juba eraldi nüüd on. :)

> kui mul on ühel nimetusel kaks sihtpunkti, siis lisan need üksteise alla?
KOV ja kogukonna ettepanekutele sihtpunkte ei teeks - kõik ettepanekud lähevad ühtmoodi kohalikele omavalitsustele ja linnade/valdade liidule. Nii võib vast tabel sellisel kujul jääda, kuid kas loenduri tarbeks oleks vaja viited ka KOV ettepanekutele lisada?

Ei, viiteid (ehk linke) ei ole loenduri tarbeks vaja. Loendamise võime teha sihtpunkti nime alusel. Mitme viite lisamiseks, jaa, eraldi rida on hea.

> Peaksime uued joonised ja tekstid lisama lehele "Tulemused", teen ikka uue faili?

Aa, ei, siis võid ka "Tulemused" faili panna. Vaatan niikuinii enne üle ja täiendan, kui midagi korrigeerida vaja. :)

> Mõtlesin jah:)

Gotcha. Lükkan kohe üles.

**Comment by moll** [comment]
@marisjogeva:
PDFid on üleval:
- https://kestame.rahvaalgatus.ee/ränne-ettepanekud.pdf
- https://kestame.rahvaalgatus.ee/sündimus-ettepanekud.pdf
- https://kestame.rahvaalgatus.ee/tööhõive-ettepanekud.pdf

**Comment by moll** [comment]
@marisjogeva:
Lisasin sihtpunktide lingid lahenduste test-lehele: https://kestame.rahvaalgatus.ee/lahendused/. Näed, mil moel neid kuvada saame. Panin nad hetkel pealkirja "Ettepanek edasi suunatud" alla, kuid seda võime ka teisiti nimetada. Kui tahaksid samasugust rasvasemat pealkirja probleemi paragrahvile, tasub sõna "Probleem:" (ja koolon) kõigpealt ettepanekute tabeli tekstidest eemaldada. (Seda võin ka ise find & replace'iga teha).

Lisasin testimiseks ka automaatselt loetletud sihtpunktide arvud samale lehele. Selle info põhjal võib siis hiljem top-5 kuvada, nagu käesolev _issue_ soovis.

**Comment by moll** [comment]
> Nii võib vast tabel sellisel kujul jääda, kuid kas loenduri tarbeks oleks vaja viited ka KOV ettepanekutele lisada?

Lugesin vist esialgu su KOV viidete küsimust valesti. Kui tahame KOVi ja vajadusel kogukondade viiteid ka kokku lugeda, siis peaksime need ka masinloetavaks tegema ehk nende jaoks eraldi tulba tegema.

**Comment by moll** [comment]
> Sa ei peaks sihtpunkte seletusse ka lisama, sest need juba eraldi nüüd on. :)

Selle täpsustuseks: Kui soovid, et sihtpunktide nimed olekski alati ka ettepanekute teksti lõpus, siis võin need ka `government_links` tulbast automaatselt lisada, ilma et peaksid neid hoidma nii sihtpunktide tulbas kui ka ettepaneku teksti lõpus, nagu praegu.

**Comment by marisjogeva** [comment]
Aga teeks nii, et jätan ettepanekusse trellid ja siis siukse modifitseeritud nime (nt MKMelamumajandus), kuid loendisse tuleb viisakam versioon (MKM elamumajanduse valdkond)?
Maris

**Comment by moll** [comment]
Võid ka nii. Jätan linkide ette trellid alles või võtan sealt ära? Kellele need trellid üldse on? Tegu pole ju Twitteriga. :P

**Comment by marisjogeva** [comment]
_PDFid on üleval:_
@moll kas saaksid need nüüd veebiga ka siduda. Avalehel viimane tabel "Lahendused probleemide kaupa" lõpus peaks olema ühe "vaata tagasisidet" nupu asemel kolm (iga tulba kohta üks), millele klikkides avaneks vastava teema tagasisidefail. 

Trellid: Kas võiks jätta nii, et ettepanekute tabeli teksti jääb viide trellidega (eesmärk on, et ilma linki avamata saad lugedes kiire vihje, kuhu ettepanek liikus). Loendisse aga tekiksid korrektsed viited - need olen siis nii palju kui võimalik proovinud ka su loodud veergu kirja panna.

**Comment by moll** [comment]
>  @moll kas saaksid need nüüd veebiga ka siduda. Avalehel viimane tabel "Lahendused probleemide kaupa" lõpus peaks olema ühe "vaata tagasisidet" nupu asemel kolm (iga tulba kohta üks), millele klikkides avaneks vastava teema tagasisidefail.

Arvasin, et need lähevad "Sõelutud Ettepanekute" tulpade alla ja sõelutute ülespanekuks ootan sult veel kinnitust. :) Kuna "Lahendused probleemide kaupa" kaob esilehelt, siis kindel, et mõtled seda?

> Trellid: Kas võiks jätta nii, et ettepanekute tabeli teksti jääb viide trellidega (eesmärk on, et ilma linki avamata saad lugedes kiire vihje, kuhu ettepanek liikus). Loendisse aga tekiksid korrektsed viited - need olen siis nii palju kui võimalik proovinud ka su loodud veergu kirja panna.

Võid ka nii jätta.

**Comment by moll** [comment]
Ka, kui tahad, et tekstis olev lingita trellikas oleks automaatselt linkide/sihtpunktide tulbast genereeritud, saab nii ka. Selleks ei pea sama infot kahes kohas haldama.

**Comment by marisjogeva** [comment]
Need 3 “tagasiside” faili on koostatud esialgsete lahendusideede pōhjal. Sõelutud ettepanekud tekkisid järgmises etapis.

Esilehele asemel sobivad nüüd nupud “tulemuste” lehel olevate samade tulpade alla. Need jäävad ju ka alles, sõelutud ettepanekute ette? Ainult esilehel vahetame “lahendused probleemide kaupa “ sõelutud ettepanekute vastu, eksju?

**Comment by moll** [comment]
> Esilehele asemel sobivad nüüd nupud “tulemuste” lehel olevate samade tulpade alla. Need jäävad ju ka alles, sõelutud ettepanekute ette?

Selge, panen PDFi lingid "Lahendused probleemide kaupa" tulpade lõppu!

> Ainult esilehel vahetame “lahendused probleemide kaupa “ sõelutud ettepanekute vastu, eksju?

Jep.

**Comment by moll** [comment]
PDFide lingid tulpade lõpus.

**Comment by moll** [comment]
Mis aga edasiste sammude kokkuvõtte visualisatsioonist saab? Linkide tulba põhjal arvutatud tulemused on hetkel https://kestame.rahvaalgatus.ee/lahendused/ lõpus näha. Mis nendega ette võtame?

**Comment by marisjogeva** [comment]
Praegu on veel vanad andmed? Olen tabelis viiteid iga päev uuendanud. 
Nende numbrite põhjal peaks sündima nüüd erinevas suuruses mummud.

**Comment by moll** [comment]
> Praegu on veel vanad andmed? Olen tabelis viiteid iga päev uuendanud.

Ununes vist peale PDFi nuppe uuendatud andmetega versioon üles lükata. :) Kae nüüd: https://kestame.rahvaalgatus.ee/lahendused/

**Comment by marisjogeva** [comment]
Aitäh! 
pdf-i nupud on täitsa OK ning mu meelest võiks ettepanekud ka laivi lubada. Kuidas saame aga “Edasised sammud” osale selle mootori taha panna, mis loetelust erinevate suurustega mummud teeb?

tervitades
Maris

**Comment by moll** [comment]
Kas mingi teine visualisatsioon rõngaste asemel parem ei oleks? Tulpdiagramm? Lihtsalt viis ringi tundub natuke lahjavõitu mu meelest. :)

**Comment by moll** [comment]
![Screenshot from 2019-03-27 21-59-34](https://user-images.githubusercontent.com/156837/55115112-a2bf0b80-50db-11e9-847a-bef0a57aed8a.png)

Panin esialgu lehe linkide ette ka trelle lisama. Tasub seda teha, @marisjogeva? Natuke kummalised mu meelest, sest tegu pole ju Twitteriga. :P

**Comment by marisjogeva** [comment]
Tervitus!
Ma sellele “ettepanek edasi suunatud” osale trelle ei paneks. Tabelisse panin ka korrektsed nimed, millele trellid ei sobikski. Mõtlen praegu, et kui “Ettepanek edasi suunatud” osa jääb, siis pole ka ettepaneku teksti järel trellidega viiteid vaja?

**Comment by moll** [comment]
> Mõtlen praegu, et kui “Ettepanek edasi suunatud” osa jääb, siis pole ka ettepaneku teksti järel trellidega viiteid vaja?

Seda minagi. :P 

Võtan aga trellid linkide eest ära.

**Comment by n2nsim** [comment]
> Kas mingi teine visualisatsioon rõngaste asemel parem ei oleks? Tulpdiagramm? Lihtsalt viis ringi tundub natuke lahjavõitu mu meelest. :)

tulbad üsna igavad, oleme neid nii palju juba kasutanud. on sul veel ettepanekuid, mida kasutada?

**Comment by moll** [comment]
@marisjogeva:
> Alamleht “Tulemused”. Ega te leidnud lahendust “edasised sammud” osa visualiseerimiseks. Prooviks ikkagi sõõre-mummusid?

Alati saab ka lihtsalt loendis numbri ja nime panna. :) Jäävad ringid? Kuidas? Horisontaalselt? Mobiili eriti horisontaalselt ei mahu. Äkki loetelu ja iga rea ees on pisut suurem ring kui järgmine? Ringi sees number? Mingi tekst ka sektsiooni ette?

**Comment by n2nsim** [comment]
@moll @marisjogeva Andri pakutu "Äkki loetelu ja iga rea ees on pisut suurem ring kui järgmine? Ringi sees number?" tundub igati ok.

**Comment by marisjogeva** [comment]
Prooviks seda lahendust jah.

**Comment by moll** [comment]
Hei! Lisasin 5 populaarseimat linki [avalehele](https://kestame.rahvaalgatus.ee/) ja tulemuste lehele siniste ringidena. Kuidas tundub? Ehk on lause või kaks ka loendile ette panna, et selle olemust seletada? Kas jätan populaarseima 5 jaoks või kuvame kõik? Ülejäänud said vist pea kõik vaid ühe lahenduse ehk punkti endale.

**Comment by n2nsim** [comment]
> Hei! Lisasin 5 populaarseimat linki [avalehele](https://kestame.rahvaalgatus.ee/) ja tulemuste lehele siniste ringidena. Kuidas tundub? Ehk on lause või kaks ka loendile ette panna, et selle olemust seletada? Kas jätan populaarseima 5 jaoks või kuvame kõik? Ülejäänud said vist pea kõik vaid ühe lahenduse ehk punkti endale.

Minu arvates 5 TOP kategooriat on ok. Olen nõus, et loendi juures paar selgitavat lauset võiks olla. Kas Sa saad need anda, @marisjogeva?

**Comment by marisjogeva** [comment]
Tervitus!
Sobib hästi. Lisasin paar lauset “tulemused” lehele. Andri, kas saad, palun, tõsta sealt ka esilehele. 
M.

**Comment by moll** [comment]
Laivis! Võib vist praegu ka selle _issue_ lõpetatuks lugeda. :) Nagu ikka, kui tahad värskeid tekste või tabelite andmeid veebilehel näha, anna lihtsalt märku. See on ühe käsu jooksutamise küsimus.
