### ISSUE TITLE
Google Analytics külge

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/kestame#3]

**Comment by moll** [comment]
Analyticsi id-d ka vaja. ;)

**Comment by infokujur** [comment]
@katjadanilova loob ja kirjutab siia lõimu, kui valmis.

**Comment by katjadanilova** [comment]
@moll 

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-122944734-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-122944734-1');
</script>

**Comment by moll** [comment]
Lükkasin https://kestame.rahvaalgatus.ee/ lehele üles. Palun testida, kas indikaatorid Google Analyticsis selle peale ka liiguvad.

**Comment by katjadanilova** [comment]
ei liikunud.
vaatasin, et kui proovida lisada selle koodi juppi, siis toimib:

  ```
window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-122944734-1');

```
kui soovid, äkki annan ligipääsu analytics kontole?

**Comment by moll** [comment]
Võid ehk korra tõesti GA ligipääsu jagada. Vaatan, miks https://github.com/rahvaalgatus/kestame/commit/6fa5d5dc4609156b9f7bc09e5f97d911b1b8a937#commitcomment-29917231 lähenemine armatuurlaua indikaatoreid ei liiguta.

**Comment by katjadanilova** [comment]
kas sellele aadressile? andri@dot.ee

**Comment by moll** [comment]
Yep.

**Comment by katjadanilova** [comment]
tehtud.

**Comment by moll** [comment]
Tuli välja, et Google Analytics on natuke totram kui esialgu arvasin. Fiksisin. Nüüd paistis analüütika töötavat.

**Comment by katjadanilova** [comment]
hurray! näitab kõike kenasti nüüd :)
