### ISSUE TITLE
Arutelude arvu summa

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/kestame#30]
@marisjogeva:
> algatuses sai igaüks osaleda - täpsustaks numbrid: Toimus 34 kogukondlikku arutelu rahvastikutrendide mõtestamiseks ja probleemidele lahenduste leidmiseks; Aruteludel osales 358 inimest, kes pakkusid ideekorjesse 90 lahendusideed.

Nagu kunagi kokku lepitud sai, tulevad numbrid arutelude tabelist. Värskendasin seda ja nüüd on 32 arutelu 350 liikmega. Soovid, et asendame staatiliste numbritega või uuendad tabelit?

**Comment by moll** [comment]
Ma teie asemel viiks tabeli vastavusse oodatud numbritega. Nõnda ei ole tulevikus kellelgi segadust, miks need kaks andmestikku erinevad.

**Comment by marisjogeva** [comment]
Täiendan algfaili kahe arutelu andmetega jaanuarikuust. Miskipärast arvasin, et enam ei ole andmed seotud.
M.

**Comment by moll** [comment]
Vahva. Anna teada, kui täiendatud.

**Comment by marisjogeva** [comment]
Hei! 
Lisasin arutelude andmed otse registreerimisvastuste vormi, kuid sellest vist ei piisa? 
No võta nüüd seda mälukest - lihtsalt ei leidnud enam kusagilt ankeedi linki. 

Ühtlasi tegin ühe muudatuse lehel “arutelud” - eelmisest korrast oli poolik lausejupp teksti lõppu jäänud.

**Comment by moll** [comment]
> Lisasin arutelude andmed otse registreerimisvastuste vormi, kuid sellest vist ei piisa? No võta nüüd seda mälukest - lihtsalt ei leidnud enam kusagilt ankeedi linki.

Tundub, et panid õigesse tabelisse. Nüüd lehel kenasti 358 osalejat.

> Ühtlasi tegin ühe muudatuse lehel “arutelud” - eelmisest korrast oli poolik lausejupp teksti lõppu jäänud.

Hmm, näen tõesti "ekute" lauset, kuid kuhu su muudatus on läinud, huvitav? https://drive.google.com/drive/folders/17AUpPMiJWnT9I-MAld5j_1wa1O-2cNAa -s asuvas arutelud.md failis on poolik lause ikka sees, kuigi viimati on ta sinu poolt muudetud...

**Comment by marisjogeva** [comment]
Hmm, mul enam seda poolikut ei näita (avasin su lingi). 
M.

**Comment by moll** [comment]
Hehe, tõepoolest. Mul näitas enne, et muutsid viimati umbes 11 paiku täna, kuid nüüd vaadates näen 20 minutit tagasi muutust. Ju siis Google ei näidanud meile esialgu identset seisu või StackEdit ei sünkroniseerinud piisavalt kiirelt.

Lükkasin uuendatud tekstiga saidi üles.
