### ISSUE TITLE
Tulemuste lehe lõpetamine

### ISSUE THREAD

**Issue by marisjogeva** [rahvaalgatus/kestame#31]
@moll tegin veel paar täpsustust alamlehe "tulemused" teksti. Sinna on tekkinud loetelu ministeeriumite nimedega, mis tuleks linkida õigete pdf-dega (viimased saab kätte: https://www.dropbox.com/sh/zqfc1y650l2rzqy/AADQ8Wt4JfI0hhXUUI2-8JD8a?dl=0). 

Eelmisel nädalal täpsustasin ka mõnda lauset ettepanekute tabelis. Sa mainisid, et nende laivi lubamiseks on vaja üht nupule vajutust:)

**Comment by moll** [comment]
Hei

Praegu on nii esilehel kui ka tulemuste lehel top-5 edasist sammu. Kuhu need paigutame? Kas paragrahv edasistest sammudest tuleb selle asemele koos linkide? Jääb ainult "tulemused" lehele?

**Comment by marisjogeva** [comment]
Ma jätaks olemasoleva joonise alles. Täiendust ei ole iseenesest esilehele vaja, kuid “tulemuste” lehel peaksid need näha olema. 
1) Kas on ka variant, et esilehel jääb nii kuis on ja täiendused lubada laivi vaid “tulemuste” lehel? Kui see keerukam, las olla kôik ka esilehel täiendatuna.
2) Jätsin viimase lisatud lause ära  ja siis tegelikult ei muutugi muud kui ainult viimast joonist sissejuhatav tekst muutub veidi pikemaks ja saab pdf-d juurde.

**Comment by moll** [comment]
Joonise all mõtled top-5 nimekirja? Nii saab küll, et ettepanekud+top5 on esilehel, kuid "Edasised Sammud" koos linkidega mitte. Ettepanekute+top5 tekst peab mõlemal aga sama olema.

> 2) Jätsin viimase lisatud lause ära ja siis tegelikult ei muutugi muud kui ainult viimast joonist sissejuhatav tekst muutub veidi pikemaks ja saab pdf-d juurde.

Võimalik, et Google ei näita mulle su viimast muudatust, sest ma näen, et viimase lingi teksti sisse on tulnud uuesti loetelu ministeeriumitest. Nagu ehk ka nägid, lisasin sõna "Ettepanekud" iga lingi ette. Nõnda on link kenasti iseseisvalt tähenduslik, mitte ei jätka lauset ülal.

Ehk siis top-5 ees on praegu tekst:
> 	Ettepanekud on asjaomastele riigiasutustele edasi antud ja kui ka kõik nendest ei ole kohe jõustamiseks toetust leidnud, jätkub arutelu kogukondades väljapakutud lahenduste üle paljude valdkondade tulevikustrateegiaid läbi rääkides. Ettepanekud puudutavad enam kui kümmet valdkonda,  kõige enam tööpoliitikat, regionaalpoliitikat, hariduspoliitikat ning laste- ja perepoliitikat. 

Kas jätan selle ja võtan ehk lihtsalt pealkirja ta eest ära, nii et ta tuleks kohe peale ettepanekute kaste?

Ettepanekute PDFide lingid aga jäävad siis "Edasised sammud" pealkirja alla koos ühe lausega?
> Projektimeeskond andis ettepanekud kirjalike kokkuvõtetena ministeeriumitele, riigikantseleile ning piirkondlikele arendustöötajatele ettepanekud järgmiselt:

Või liigutame top-5 paragrahvi "Edasised sammud" alla ja paigutame enne PDFi linke? Nõnda kaob ta küll esilehelt, kui on koos kokkuvõttega.

**Comment by marisjogeva** [comment]
Jube segaseks läks:) 
Kas võib jääda nii: 

pealkiri Edasised sammud
tekst: Projektimeeskond….järgmiselt (jätkub loetelu)
tekst: Kui kõik ideed …..
joonis top5

“Ettepanekud” võib olla ministeeriumi nime ees küll

tervitades
Maris

**Comment by moll** [comment]
Hehe, kahtlustasin, jah, et sellest _rääkimine_ ei ole kõige lihtsam. :P Liigutasin top5 muu teksti alla ja eemaldasin ta eelneva sissejuhatuse (koopia all). Viska pilk peale: https://kestame.rahvaalgatus.ee/tulemused/.

> 	Ettepanekud on asjaomastele riigiasutustele edasi antud ja kui ka kõik nendest ei ole kohe jõustamiseks toetust leidnud, jätkub arutelu kogukondades väljapakutud lahenduste üle paljude valdkondade tulevikustrateegiaid läbi rääkides. Ettepanekud puudutavad enam kui kümmet valdkonda,  kõige enam tööpoliitikat, regionaalpoliitikat, hariduspoliitikat ning laste- ja perepoliitikat.

**Comment by moll** [comment]
Võib vist eeldada, et kõik laabus edukalt. :) Head uue aasta jätku ka!

**Comment by marisjogeva** [comment]
Head uue aasta jätku Sullegi! 
Oli väga meeldiv koos töötada. Kõik laabus, aitäh!

tervitustega
Maris
