### ISSUE TITLE
Staatiline kaart avalehele

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/kestame#4]
Kaart: https://toolbox.estonia.ee/media/1861
Joonised: https://toolbox.estonia.ee/media/950, https://toolbox.estonia.ee/media/984, https://toolbox.estonia.ee/media/1004

**Comment by moll** [comment]
Käsitleme seda ka edasi läbi https://github.com/rahvaalgatus/kestame/issues/10.
