### ISSUE TITLE
Interaktiivne kaart

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/kestame#5]
Kaart: https://toolbox.estonia.ee/media/1861 (esialgu pildina staatiline, II etappi jooksul on seda tarvis animeerida. Kui tulevad juurde arutelud, siis seda annab muuta interaktiivseks nönda: kui hiirega kasutaja liigub mõni maakonna peale, maakonna värv muutub valgeks, ilmub pop-up koos arutelude nimekirjaga ja muude vajalikke linkidega konkreetselt selle maakonna lõikes. Hiljem saab juurde ka heat-map teha (ehk aktiivsemad kohad on tumedamad kui passiivsemad). Näeb puhtamana välja ja on veidi rohkem kasutajasõbralik kui tavaline kaart.)
Joonised: https://toolbox.estonia.ee/media/950, https://toolbox.estonia.ee/media/984, https://toolbox.estonia.ee/media/1004

**Comment by infokujur** [comment]
Räägime selle - kuidas animeerida siis läbi, kui teine etapp võtab terviklikuma vormi.

**Comment by infokujur** [comment]
#4 Selle jätk

**Comment by infokujur** [comment]
#12

**Comment by infokujur** [comment]
#8

**Comment by moll** [comment]
Sulgen, kuna tänaseks tehtud ja ammu laivis.
