### ISSUE TITLE
Loendur .md kaudu muudetav

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/kestame#6]

**Comment by infokujur** [comment]
Küsimus: Kas see hakkab ka oma infot mingil muul ajal kuskilt koguma?

**Comment by moll** [comment]
Markdowni teda hetkel ei liigutanud, sest tegu ainult kahe numbriga. Muudetav kasvõi siin samas läbi GitHubi editori https://github.com/rahvaalgatus/kestame/blob/master/content/home.haml failis.

**Comment by katjadanilova** [comment]
hea oleks, et muuta saaks kõiki asju ühes failis, ehk ka seda seal, kus tekstid on. Muutusi teen mitte mina, vaid kolmas isik ja tglt ei ole hea, kui neil ligipääs koodile on :) 
@infokujur mis arvad?

**Comment by infokujur** [comment]
@katjadanilova Usun, et muret ei ole, kuna siin muutes ei muutu see automaatselt vaid selleks peab ühe nupulevajutuse veel tegema (Andri).
Kui kolmandal isikul on ka Githubi konto, siis selle järgi saab näha, et ei ole keegi tundmatu.
Teksti failidsse saab panna selle lingi - nii kolmas isik ei pea ise otsimas käima, vaid tal on kohe selge, mida vaja muuta.

Aga peamine - see on ajutine olukord - seniks kuni ankeedid ka ühendame. Siis see käsitöö laheneb ja see number hakkab tulema kuskilt Gsheetsist, mis ise kokku arvutab.

**Comment by katjadanilova** [comment]
nüüd kõik selge, tänan selgistuste eest!

**Comment by katjadanilova** [comment]
@moll muutsin arutelude ja osalejate arv.

**Comment by moll** [comment]
Lükkasin üles.

**Comment by katjadanilova** [comment]
@moll tegin mõned muudatused avalehel, sh loenduris.
kas me saaksime nüüd loenduri ühendada tulemuste ankeediga? et ei peaks käsitsi selle tegema?
ei leia nüüd selle arutelu ülesse, seega küsin - kas avalehe tekste oli ka plaanis .md failidesse lükkata?

**Comment by moll** [comment]
Loenduri arutelu jätkub https://github.com/rahvaalgatus/kestame/issues/6.

Avalehe tekste tervikuna praegu polnud plaanis _Markdownida_, sest igaühte on vaid üks paragrahv ja kõik eraldi ning ümbritsetud küljenduse pärast HTMLiga. Kas mõni neist tahab rohkem muutmist, et eraldi Markdowni faili liigutamine selle lihtsamaks teeks? GitHubi editorist, millega sa vist muutused teinud oled, jääb puudu?
