### ISSUE TITLE
II ankeet - Arutelu tulemuste Google Forms ankeet

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/kestame#7]
Lahenduste ideekorje nii onlainis kui aruteludelt, ettepanekute esitamiseks ja arutelu tulemuste salvestamiseks täidetakse Google Forms ankeet.

**Comment by infokujur** [comment]
See tuleb II etapis.

**Comment by infokujur** [comment]
Ankeet - https://docs.google.com/forms/d/1A-VX7TsccxmtIdKC0-qR3q96kWOQqnEbbcTP_LUhBeQ

**Comment by infokujur** [comment]
@katjadanilova - kas see vajab ka eraldi stiliseerimist (kuigi saadetakse eraldi), et oleks sarnane teistega?

**Comment by katjadanilova** [comment]
eraldi stiliseerimist ei vaja.

**Comment by moll** [comment]
Sulgen, kuna https://github.com/rahvaalgatus/kestame/issues/13 ja https://github.com/rahvaalgatus/kestame/issues/14 tunduvad samad.
