### ISSUE TITLE
II ankeet - Arutelu tulemuste Google Forms ankeet tulemuste kuva

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/kestame#8]

**Comment by infokujur** [comment]
Siia midagi sellest ankeedist #6

**Comment by infokujur** [comment]
a) muutub arutelude arv avalehel; 
b) muutub osalejate arv avalehel

Midagi juhtub ka kaardil, aga see veel tuleb.

**Comment by infokujur** [comment]
@moll  https://docs.google.com/forms/d/1EK_Q9Ro-gzRDQ8TbJu0UvNfplIvNhJhI0mpoDruqZ-M/edit

Siin õige ankeet.

**Comment by moll** [comment]
Saatsin access request päringu ka ankeedi poole teele. Tundub, et selleta ei näe tulemusi ja tabelit, kuhu sõnapilved jm kirja saavad.

**Comment by katjadanilova** [comment]
õigused antud. kui soovid, võin paroolid ka saata.

**Comment by moll** [comment]
Mille paroolid? :)

Sain Formsi telgitagused ette, kuid tabeli avamiseks, tuleb välja, vaja veel lisakinnitust. Saatsin päringu teele. :)

**Comment by katjadanilova** [comment]
google account paroolid, kes selle ankeedi omanik on (meil on eraldi konto selle ankeedi jaoks loodud).
aga andsin praegu õigused.

**Comment by moll** [comment]
Sulgen, kuna https://github.com/rahvaalgatus/kestame/issues/13 ja https://github.com/rahvaalgatus/kestame/issues/14 tunduvad samad.
