### ISSUE TITLE
kestame.rahvaalgatus.ee toomine rahvaalgatus.ee külge

### ISSUE THREAD

**Issue by infokujur** [rahvaalgatus/kestame#9]
Mõjukate ettepanekute esitamine allkirjade kogumiseks olemasoleva lahenduse baasil ehk rahvaalgatus.ee mootori taha toomine.

**Comment by infokujur** [comment]
Praegu on veel lahtine, kuidas sõelutakse mõjukad ettepanekud?
Mis etapis?

**Comment by moll** [comment]
Sulgeksin selle issue, kuniks #kuidasmekestame + RA uuesti teemaks tuleb. Vaevalt ta vahepeal kogemata meelest läheb. :)
